/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db;


import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.tables.Orderitems;
import com.tokenplay.ue4.model.db.tables.Orders;
import com.tokenplay.ue4.model.db.tables.Products;
import com.tokenplay.ue4.model.db.tables.Profiles;
import com.tokenplay.ue4.model.db.tables.Tue4Allegiance;
import com.tokenplay.ue4.model.db.tables.Tue4BmAccountmaster;
import com.tokenplay.ue4.model.db.tables.Tue4BmAccounts;
import com.tokenplay.ue4.model.db.tables.Tue4BmAssets;
import com.tokenplay.ue4.model.db.tables.Tue4BmCorporations;
import com.tokenplay.ue4.model.db.tables.Tue4BmOrder;
import com.tokenplay.ue4.model.db.tables.Tue4BmPayee;
import com.tokenplay.ue4.model.db.tables.Tue4BmTransactions;
import com.tokenplay.ue4.model.db.tables.Tue4Championship;
import com.tokenplay.ue4.model.db.tables.Tue4ConfigItem;
import com.tokenplay.ue4.model.db.tables.Tue4EquipmentAwarded;
import com.tokenplay.ue4.model.db.tables.Tue4EventScore;
import com.tokenplay.ue4.model.db.tables.Tue4GameMode;
import com.tokenplay.ue4.model.db.tables.Tue4GearInstance;
import com.tokenplay.ue4.model.db.tables.Tue4GearModel;
import com.tokenplay.ue4.model.db.tables.Tue4GearSection;
import com.tokenplay.ue4.model.db.tables.Tue4GearSectionConfiguration;
import com.tokenplay.ue4.model.db.tables.Tue4InventoryInstance;
import com.tokenplay.ue4.model.db.tables.Tue4InventoryLocation;
import com.tokenplay.ue4.model.db.tables.Tue4InventoryObject;
import com.tokenplay.ue4.model.db.tables.Tue4Leaderboard;
import com.tokenplay.ue4.model.db.tables.Tue4LoreCircuits;
import com.tokenplay.ue4.model.db.tables.Tue4LoreCorporations;
import com.tokenplay.ue4.model.db.tables.Tue4LoreEarthtimeline;
import com.tokenplay.ue4.model.db.tables.Tue4LoreEquipment;
import com.tokenplay.ue4.model.db.tables.Tue4LoreGears;
import com.tokenplay.ue4.model.db.tables.Tue4LoreHolidays;
import com.tokenplay.ue4.model.db.tables.Tue4LoreLocations;
import com.tokenplay.ue4.model.db.tables.Tue4LorePlanets;
import com.tokenplay.ue4.model.db.tables.Tue4LoreStars;
import com.tokenplay.ue4.model.db.tables.Tue4LoreTaxes;
import com.tokenplay.ue4.model.db.tables.Tue4Map;
import com.tokenplay.ue4.model.db.tables.Tue4Mapcycle;
import com.tokenplay.ue4.model.db.tables.Tue4Mapmode;
import com.tokenplay.ue4.model.db.tables.Tue4Match;
import com.tokenplay.ue4.model.db.tables.Tue4MatchEvent;
import com.tokenplay.ue4.model.db.tables.Tue4MatchSession;
import com.tokenplay.ue4.model.db.tables.Tue4MatchSessionParticipant;
import com.tokenplay.ue4.model.db.tables.Tue4Message;
import com.tokenplay.ue4.model.db.tables.Tue4PaintScheme;
import com.tokenplay.ue4.model.db.tables.Tue4Participation;
import com.tokenplay.ue4.model.db.tables.Tue4Pilot;
import com.tokenplay.ue4.model.db.tables.Tue4PledgeAwarded;
import com.tokenplay.ue4.model.db.tables.Tue4Ranking;
import com.tokenplay.ue4.model.db.tables.Tue4Registration;
import com.tokenplay.ue4.model.db.tables.Tue4Relationship;
import com.tokenplay.ue4.model.db.tables.Tue4ScoreConfig;
import com.tokenplay.ue4.model.db.tables.Tue4Server;
import com.tokenplay.ue4.model.db.tables.Tue4ServerAuthorised;
import com.tokenplay.ue4.model.db.tables.Tue4Stable;
import com.tokenplay.ue4.model.db.tables.Tue4UiAttribute;
import com.tokenplay.ue4.model.db.tables.Tue4UiTheme;
import com.tokenplay.ue4.model.db.tables.Tue4UiThemeAttribute;
import com.tokenplay.ue4.model.db.tables.Users;


/**
 * Convenience access to all tables in
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>orderitems</code>.
     */
    public static final Orderitems ORDERITEMS = com.tokenplay.ue4.model.db.tables.Orderitems.ORDERITEMS;

    /**
     * The table <code>orders</code>.
     */
    public static final Orders ORDERS = com.tokenplay.ue4.model.db.tables.Orders.ORDERS;

    /**
     * The table <code>products</code>.
     */
    public static final Products PRODUCTS = com.tokenplay.ue4.model.db.tables.Products.PRODUCTS;

    /**
     * The table <code>profiles</code>.
     */
    public static final Profiles PROFILES = com.tokenplay.ue4.model.db.tables.Profiles.PROFILES;

    /**
     * The table <code>tue4_allegiance</code>.
     */
    public static final Tue4Allegiance ALLEGIANCE = com.tokenplay.ue4.model.db.tables.Tue4Allegiance.ALLEGIANCE;

    /**
     * The table <code>tue4_bm_accountmaster</code>.
     */
    public static final Tue4BmAccountmaster BM_ACCOUNTMASTER = com.tokenplay.ue4.model.db.tables.Tue4BmAccountmaster.BM_ACCOUNTMASTER;

    /**
     * The table <code>tue4_bm_accounts</code>.
     */
    public static final Tue4BmAccounts BM_ACCOUNTS = com.tokenplay.ue4.model.db.tables.Tue4BmAccounts.BM_ACCOUNTS;

    /**
     * The table <code>tue4_bm_assets</code>.
     */
    public static final Tue4BmAssets BM_ASSETS = com.tokenplay.ue4.model.db.tables.Tue4BmAssets.BM_ASSETS;

    /**
     * The table <code>tue4_bm_corporations</code>.
     */
    public static final Tue4BmCorporations BM_CORPORATIONS = com.tokenplay.ue4.model.db.tables.Tue4BmCorporations.BM_CORPORATIONS;

    /**
     * The table <code>tue4_bm_order</code>.
     */
    public static final Tue4BmOrder BM_ORDER = com.tokenplay.ue4.model.db.tables.Tue4BmOrder.BM_ORDER;

    /**
     * The table <code>tue4_bm_payee</code>.
     */
    public static final Tue4BmPayee BM_PAYEE = com.tokenplay.ue4.model.db.tables.Tue4BmPayee.BM_PAYEE;

    /**
     * The table <code>tue4_bm_transactions</code>.
     */
    public static final Tue4BmTransactions BM_TRANSACTIONS = com.tokenplay.ue4.model.db.tables.Tue4BmTransactions.BM_TRANSACTIONS;

    /**
     * The table <code>tue4_championship</code>.
     */
    public static final Tue4Championship CHAMPIONSHIP = com.tokenplay.ue4.model.db.tables.Tue4Championship.CHAMPIONSHIP;

    /**
     * The table <code>tue4_config_item</code>.
     */
    public static final Tue4ConfigItem CONFIG_ITEM = com.tokenplay.ue4.model.db.tables.Tue4ConfigItem.CONFIG_ITEM;

    /**
     * The table <code>tue4_equipment_awarded</code>.
     */
    public static final Tue4EquipmentAwarded EQUIPMENT_AWARDED = com.tokenplay.ue4.model.db.tables.Tue4EquipmentAwarded.EQUIPMENT_AWARDED;

    /**
     * The table <code>tue4_event_score</code>.
     */
    public static final Tue4EventScore EVENT_SCORE = com.tokenplay.ue4.model.db.tables.Tue4EventScore.EVENT_SCORE;

    /**
     * The table <code>tue4_game_mode</code>.
     */
    public static final Tue4GameMode GAME_MODE = com.tokenplay.ue4.model.db.tables.Tue4GameMode.GAME_MODE;

    /**
     * The table <code>tue4_gear_instance</code>.
     */
    public static final Tue4GearInstance GEAR_INSTANCE = com.tokenplay.ue4.model.db.tables.Tue4GearInstance.GEAR_INSTANCE;

    /**
     * The table <code>tue4_gear_model</code>.
     */
    public static final Tue4GearModel GEAR_MODEL = com.tokenplay.ue4.model.db.tables.Tue4GearModel.GEAR_MODEL;

    /**
     * The table <code>tue4_gear_section</code>.
     */
    public static final Tue4GearSection GEAR_SECTION = com.tokenplay.ue4.model.db.tables.Tue4GearSection.GEAR_SECTION;

    /**
     * The table <code>tue4_gear_section_configuration</code>.
     */
    public static final Tue4GearSectionConfiguration GEAR_SECTION_CONFIGURATION =
        com.tokenplay.ue4.model.db.tables.Tue4GearSectionConfiguration.GEAR_SECTION_CONFIGURATION;

    /**
     * The table <code>tue4_inventory_instance</code>.
     */
    public static final Tue4InventoryInstance INVENTORY_INSTANCE = com.tokenplay.ue4.model.db.tables.Tue4InventoryInstance.INVENTORY_INSTANCE;

    /**
     * The table <code>tue4_inventory_location</code>.
     */
    public static final Tue4InventoryLocation INVENTORY_LOCATION = com.tokenplay.ue4.model.db.tables.Tue4InventoryLocation.INVENTORY_LOCATION;

    /**
     * The table <code>tue4_inventory_object</code>.
     */
    public static final Tue4InventoryObject INVENTORY_OBJECT = com.tokenplay.ue4.model.db.tables.Tue4InventoryObject.INVENTORY_OBJECT;

    /**
     * The table <code>tue4_leaderboard</code>.
     */
    public static final Tue4Leaderboard LEADERBOARD = com.tokenplay.ue4.model.db.tables.Tue4Leaderboard.LEADERBOARD;

    /**
     * The table <code>tue4_lore_circuits</code>.
     */
    public static final Tue4LoreCircuits LORE_CIRCUITS = com.tokenplay.ue4.model.db.tables.Tue4LoreCircuits.LORE_CIRCUITS;

    /**
     * The table <code>tue4_lore_corporations</code>.
     */
    public static final Tue4LoreCorporations LORE_CORPORATIONS = com.tokenplay.ue4.model.db.tables.Tue4LoreCorporations.LORE_CORPORATIONS;

    /**
     * The table <code>tue4_lore_earthtimeline</code>.
     */
    public static final Tue4LoreEarthtimeline LORE_EARTHTIMELINE = com.tokenplay.ue4.model.db.tables.Tue4LoreEarthtimeline.LORE_EARTHTIMELINE;

    /**
     * The table <code>tue4_lore_equipment</code>.
     */
    public static final Tue4LoreEquipment LORE_EQUIPMENT = com.tokenplay.ue4.model.db.tables.Tue4LoreEquipment.LORE_EQUIPMENT;

    /**
     * The table <code>tue4_lore_gears</code>.
     */
    public static final Tue4LoreGears LORE_GEARS = com.tokenplay.ue4.model.db.tables.Tue4LoreGears.LORE_GEARS;

    /**
     * The table <code>tue4_lore_holidays</code>.
     */
    public static final Tue4LoreHolidays LORE_HOLIDAYS = com.tokenplay.ue4.model.db.tables.Tue4LoreHolidays.LORE_HOLIDAYS;

    /**
     * The table <code>tue4_lore_locations</code>.
     */
    public static final Tue4LoreLocations LORE_LOCATIONS = com.tokenplay.ue4.model.db.tables.Tue4LoreLocations.LORE_LOCATIONS;

    /**
     * The table <code>tue4_lore_planets</code>.
     */
    public static final Tue4LorePlanets LORE_PLANETS = com.tokenplay.ue4.model.db.tables.Tue4LorePlanets.LORE_PLANETS;

    /**
     * The table <code>tue4_lore_stars</code>.
     */
    public static final Tue4LoreStars LORE_STARS = com.tokenplay.ue4.model.db.tables.Tue4LoreStars.LORE_STARS;

    /**
     * The table <code>tue4_lore_taxes</code>.
     */
    public static final Tue4LoreTaxes LORE_TAXES = com.tokenplay.ue4.model.db.tables.Tue4LoreTaxes.LORE_TAXES;

    /**
     * The table <code>tue4_map</code>.
     */
    public static final Tue4Map MAP = com.tokenplay.ue4.model.db.tables.Tue4Map.MAP;

    /**
     * The table <code>tue4_mapcycle</code>.
     */
    public static final Tue4Mapcycle MAPCYCLE = com.tokenplay.ue4.model.db.tables.Tue4Mapcycle.MAPCYCLE;

    /**
     * The table <code>tue4_mapmode</code>.
     */
    public static final Tue4Mapmode MAPMODE = com.tokenplay.ue4.model.db.tables.Tue4Mapmode.MAPMODE;

    /**
     * The table <code>tue4_match</code>.
     */
    public static final Tue4Match MATCH = com.tokenplay.ue4.model.db.tables.Tue4Match.MATCH;

    /**
     * The table <code>tue4_match_event</code>.
     */
    public static final Tue4MatchEvent MATCH_EVENT = com.tokenplay.ue4.model.db.tables.Tue4MatchEvent.MATCH_EVENT;

    /**
     * The table <code>tue4_match_session</code>.
     */
    public static final Tue4MatchSession MATCH_SESSION = com.tokenplay.ue4.model.db.tables.Tue4MatchSession.MATCH_SESSION;

    /**
     * The table <code>tue4_match_session_participant</code>.
     */
    public static final Tue4MatchSessionParticipant MATCH_SESSION_PARTICIPANT =
        com.tokenplay.ue4.model.db.tables.Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT;

    /**
     * The table <code>tue4_message</code>.
     */
    public static final Tue4Message MESSAGE = com.tokenplay.ue4.model.db.tables.Tue4Message.MESSAGE;

    /**
     * The table <code>tue4_paint_scheme</code>.
     */
    public static final Tue4PaintScheme PAINT_SCHEME = com.tokenplay.ue4.model.db.tables.Tue4PaintScheme.PAINT_SCHEME;

    /**
     * The table <code>tue4_participation</code>.
     */
    public static final Tue4Participation PARTICIPATION = com.tokenplay.ue4.model.db.tables.Tue4Participation.PARTICIPATION;

    /**
     * The table <code>tue4_pilot</code>.
     */
    public static final Tue4Pilot PILOT = com.tokenplay.ue4.model.db.tables.Tue4Pilot.PILOT;

    /**
     * The table <code>tue4_pledge_awarded</code>.
     */
    public static final Tue4PledgeAwarded PLEDGE_AWARDED = com.tokenplay.ue4.model.db.tables.Tue4PledgeAwarded.PLEDGE_AWARDED;

    /**
     * The table <code>tue4_ranking</code>.
     */
    public static final Tue4Ranking RANKING = com.tokenplay.ue4.model.db.tables.Tue4Ranking.RANKING;

    /**
     * The table <code>tue4_registration</code>.
     */
    public static final Tue4Registration REGISTRATION = com.tokenplay.ue4.model.db.tables.Tue4Registration.REGISTRATION;

    /**
     * The table <code>tue4_relationship</code>.
     */
    public static final Tue4Relationship RELATIONSHIP = com.tokenplay.ue4.model.db.tables.Tue4Relationship.RELATIONSHIP;

    /**
     * The table <code>tue4_score_config</code>.
     */
    public static final Tue4ScoreConfig SCORE_CONFIG = com.tokenplay.ue4.model.db.tables.Tue4ScoreConfig.SCORE_CONFIG;

    /**
     * The table <code>tue4_server</code>.
     */
    public static final Tue4Server SERVER = com.tokenplay.ue4.model.db.tables.Tue4Server.SERVER;

    /**
     * The table <code>tue4_server_authorised</code>.
     */
    public static final Tue4ServerAuthorised SERVER_AUTHORISED = com.tokenplay.ue4.model.db.tables.Tue4ServerAuthorised.SERVER_AUTHORISED;

    /**
     * The table <code>tue4_stable</code>.
     */
    public static final Tue4Stable STABLE = com.tokenplay.ue4.model.db.tables.Tue4Stable.STABLE;

    /**
     * The table <code>tue4_ui_attribute</code>.
     */
    public static final Tue4UiAttribute UI_ATTRIBUTE = com.tokenplay.ue4.model.db.tables.Tue4UiAttribute.UI_ATTRIBUTE;

    /**
     * The table <code>tue4_ui_theme</code>.
     */
    public static final Tue4UiTheme UI_THEME = com.tokenplay.ue4.model.db.tables.Tue4UiTheme.UI_THEME;

    /**
     * The table <code>tue4_ui_theme_attribute</code>.
     */
    public static final Tue4UiThemeAttribute UI_THEME_ATTRIBUTE = com.tokenplay.ue4.model.db.tables.Tue4UiThemeAttribute.UI_THEME_ATTRIBUTE;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = com.tokenplay.ue4.model.db.tables.Users.USERS;
}
