
CREATE TABLE Tue4_UI_ATTRIBUTE (
                UAT_ID VARCHAR(32) NOT NULL,
                UAT_NAME VARCHAR(150) NOT NULL,
                UAT_DESCRIPTION VARCHAR(350),
                CONSTRAINT Tue4_UI_ATTRIBUTE_PK PRIMARY KEY (UAT_ID)
);


CREATE TABLE Tue4_LEADERBOARD (
                LEB_ID VARCHAR(32) NOT NULL,
                LEB_NAME VARCHAR(200) NOT NULL,
                LEB_DESCRIPTION VARCHAR(2048) NOT NULL,
                LEB_SCORE_FORMULA VARCHAR(4096) NOT NULL,
                CONSTRAINT Tue4_LEADERBOARD_PK PRIMARY KEY (LEB_ID)
);


CREATE TABLE Tue4_STABLE (
                STA_ID VARCHAR(32) NOT NULL,
                STA_NAME VARCHAR(250) NOT NULL,
                CONSTRAINT Tue4_STABLE_PK PRIMARY KEY (STA_ID)
);


CREATE TABLE Tue4_INVENTORY_LOCATION (
                INL_ID VARCHAR(32) NOT NULL,
                INL_NAME VARCHAR(250) NOT NULL,
                INL_SIZE INT NOT NULL DEFAULT 1,
                INL_RESTRICTED_TYPE VARCHAR(45),
                CONSTRAINT Tue4_INVENTORY_LOCATION_PK PRIMARY KEY (INL_ID)
);


CREATE TABLE Tue4_GAME_MODE (
                GAM_ID VARCHAR(150) NOT NULL,
                GAM_ASSET_NAME VARCHAR(255),
                CONSTRAINT Tue4_GAME_MODE_PK PRIMARY KEY (GAM_ID)
);


CREATE TABLE users (
                id INTEGER NOT NULL,
                profile_id INTEGER NOT NULL,
                email VARCHAR(320) NOT NULL,
                password VARCHAR(64) NOT NULL,
                role INTEGER NOT NULL,
                active BIT NOT NULL,
                role_id BIGINT DEFAULT 1 NOT NULL,
                firstname VARCHAR(255),
                lastname VARCHAR(255),
                language VARCHAR(5),
                deleted INTEGER DEFAULT 0 NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                remember_token VARCHAR(100),
                referred_by_code VARCHAR(256),
                confirmation_code VARCHAR(256),
                mod INTEGER,
                alpha BIT DEFAULT 0 NOT NULL,
                nda BIT DEFAULT 0 NOT NULL,
                eula BIT,
                CONSTRAINT users_PK PRIMARY KEY (id)
);


CREATE UNIQUE INDEX users_email_unique
 ON users
 ( email ASC );

CREATE TABLE Tue4_INVENTORY_OBJECT (
                INO_ID VARCHAR(32) NOT NULL,
                INO_NAME VARCHAR(250) NOT NULL,
                INO_BLU_MASTER VARCHAR(150),
								INO_SIZE INT NOT NULL DEFAULT 1,
								INO_TYPE VARCHAR(45),
                CONSTRAINT Tue4_INVENTORY_OBJECT_PK PRIMARY KEY (INO_ID)
);


CREATE TABLE Tue4_UI_THEME (
                UTH_ID VARCHAR(32) NOT NULL,
                UTH_NAME VARCHAR(150) NOT NULL,
                UTH_DESCRIPTION VARCHAR(2048),
                CONSTRAINT Tue4_UI_THEME_PK PRIMARY KEY (UTH_ID)
);


CREATE UNIQUE INDEX Kue4_UTH_NAME_UK
 ON Tue4_UI_THEME
 ( UTH_NAME ASC );

CREATE TABLE Tue4_UI_THEME_ATTRIBUTE (
                UTA_ID VARCHAR(32) NOT NULL,
                UTA_UTH_ID VARCHAR(32) NOT NULL,
                UTA_UAT_ID VARCHAR(32) NOT NULL,
                UTA_VALUE VARCHAR(150) NOT NULL,
                CONSTRAINT Tue4_UI_THEME_ATTRIBUTE_PK PRIMARY KEY (UTA_ID)
);


CREATE UNIQUE INDEX Kue4_UTA_UTH_ID_NAME_UK
 ON Tue4_UI_THEME_ATTRIBUTE
 ( UTA_UTH_ID ASC, UTA_UAT_ID ASC );

CREATE INDEX Kue4_UTA_AUT_FK
 ON Tue4_UI_THEME_ATTRIBUTE
 ( UTA_UAT_ID ASC );

CREATE TABLE Tue4_CHAMPIONSHIP (
                CHA_ID VARCHAR(32) NOT NULL,
                CHA_NAME VARCHAR(250) NOT NULL,
                CHA_DESCRIPTION VARCHAR(2048) NOT NULL,
                CHA_DATE_INIT DATE NOT NULL,
                CHA_DATE_END DATE NOT NULL,
                CONSTRAINT Tue4_CHAMPIONSHIP_PK PRIMARY KEY (CHA_ID)
);


CREATE TABLE Tue4_MAP (
                MAP_ID VARCHAR(150) NOT NULL,
                MAP_ASSET_NAME VARCHAR(250),
                CONSTRAINT Tue4_MAP_PK PRIMARY KEY (MAP_ID)
);


CREATE TABLE tue4_gear_section (
                GES_ID VARCHAR(32) NOT NULL,
                GES_NAME VARCHAR(150) NOT NULL,
                GES_TYPE VARCHAR(45) NOT NULL,
                CONSTRAINT tue4_gear_section_PK PRIMARY KEY (GES_ID)
);


CREATE TABLE tue4_gear_model (
                GEM_ID VARCHAR(32) NOT NULL,
                GEM_BLU_MASTER VARCHAR(150),
                GEM_BLU_ENGINE VARCHAR(150),
                GEM_BLU_FUEL_TANK VARCHAR(150),
                GEM_BLU_PYLON_RIGHT VARCHAR(150),
                GEM_BLU_PYLON_LEFT VARCHAR(150),
                GEM_BLU_HEAD VARCHAR(150),
                GEM_BLU_HIP VARCHAR(150),
                GEM_BLU_TORSO VARCHAR(150),
                GEM_BLU_FOOT_RIGHT VARCHAR(150),
                GEM_BLU_FOOT_LEFT VARCHAR(150),
                GEM_BLU_UPPER_LEG_RIGHT VARCHAR(150),
                GEM_BLU_UPPER_LEG_LEFT VARCHAR(150),
                GEM_BLU_LOWER_LEG_RIGHT VARCHAR(150),
                GEM_BLU_LOWER_LEG_LEFT VARCHAR(150),
                GEM_BLU_HAND_RIGHT VARCHAR(150),
                GEM_BLU_HAND_LEFT VARCHAR(150),
                GEM_BLU_LOWER_ARM_RIGHT VARCHAR(150),
                GEM_BLU_LOWER_ARM_LEFT VARCHAR(150),
                GEM_BLU_UPPER_ARM_RIGHT VARCHAR(150),
                GEM_BLU_UPPER_ARM_LEFT VARCHAR(150),
                GEM_BLU_SHOULDER_RIGHT VARCHAR(150),
                GEM_BLU_SHOULDER_LEFT VARCHAR(150),
                GEM_NAME VARCHAR(100) NOT NULL,
                GEM_SELECTABLE BIT DEFAULT 0 NOT NULL,
                GEM_GES_ENGINE VARCHAR(32) NOT NULL,
                GEM_GES_FUEL_TANK VARCHAR(32) NOT NULL,
                GEM_GES_PYLON_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_PYLON_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_FOOT_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_FOOT_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_UPPER_LEG_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_UPPER_LEG_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_LOWER_LEG_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_LOWER_LEG_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_HAND_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_HAND_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_LOWER_ARM_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_LOWER_ARM_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_UPPER_ARM_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_UPPER_ARM_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_SHOULDER_RIGHT VARCHAR(32) NOT NULL,
                GEM_GES_SHOULDER_LEFT VARCHAR(32) NOT NULL,
                GEM_GES_HEAD VARCHAR(32) NOT NULL,
                GEM_GES_HIP VARCHAR(32) NOT NULL,
                GEM_GES_TORSO VARCHAR(32) NOT NULL,
                CONSTRAINT tue4_gear_model_PK PRIMARY KEY (GEM_ID)
);


CREATE INDEX Kue4_GEM_GEIS_ENGINE_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_ENGINE ASC );

CREATE INDEX Kue4_GEM_GEIS_FUEL_TANK_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_FUEL_TANK ASC );

CREATE INDEX Kue4_GEM_GEIS_PYLON_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_PYLON_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_PYLON_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_PYLON_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_FOOT_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_FOOT_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_FOOT_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_FOOT_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_UPPER_LEG_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_UPPER_LEG_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_UPPER_LEG_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_UPPER_LEG_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_LOWER_LEG_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_LOWER_LEG_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_LOWER_LEG_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_LOWER_LEG_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_HAND_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_HAND_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_HAND_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_HAND_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_LOWER_ARM_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_LOWER_ARM_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_LOWER_ARM_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_LOWER_ARM_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_UPPER_ARM_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_UPPER_ARM_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_UPPER_ARM_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_UPPER_ARM_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_SHOULDER_RIGHT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_SHOULDER_RIGHT ASC );

CREATE INDEX Kue4_GEM_GEIS_SHOULDER_LEFT_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_SHOULDER_LEFT ASC );

CREATE INDEX Kue4_GEM_GEIS_HEAD_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_HEAD ASC );

CREATE INDEX Kue4_GEM_GEIS_HIP_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_HIP ASC );

CREATE INDEX Kue4_GEM_GEIS_TORSO_FK_IDX
 ON tue4_gear_model
 ( GEM_GES_TORSO ASC );

CREATE TABLE tue4_gear_section_configuration (
                GSC_ID VARCHAR(32) NOT NULL,
                GSC_GES_ID VARCHAR(32) NOT NULL,
                GSC_PROPERTY_NAME VARCHAR(150) NOT NULL,
                GSC_VALUE VARCHAR(100) NOT NULL,
                CONSTRAINT tue4_gear_section_configuration_PK PRIMARY KEY (GSC_ID)
);


CREATE INDEX Kue4_GSC_GES_ID_FK_idx
 ON tue4_gear_section_configuration
 ( GSC_GES_ID ASC );

CREATE TABLE Tue4_MAPMODE (
                MAM_ID VARCHAR(40) NOT NULL,
                MAM_GAM_ID VARCHAR(150) NOT NULL,
                MAM_MAP_ID VARCHAR(150) NOT NULL,
                MAM_ENABLED BIT DEFAULT 0 NOT NULL,
                MAM_AI_ENABLED BIT DEFAULT 0 NOT NULL,
                MAM_SRV_ID VARCHAR(32),
                MAM_MATCH_TIME INTEGER,
                CONSTRAINT Tue4_MAPMODE_PK PRIMARY KEY (MAM_ID)
);


CREATE INDEX Kue4_MAP_GAM_FK
 ON Tue4_MAPMODE
 ( MAM_GAM_ID ASC );

CREATE INDEX Kue4_MAM_SRV_FK_idx
 ON Tue4_MAPMODE
 ( MAM_SRV_ID ASC );

CREATE TABLE profiles (
                id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                callsign VARCHAR(128) NOT NULL,
                bio LONGVARCHAR,
                location VARCHAR(320),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                CONSTRAINT profiles_PK PRIMARY KEY (id)
);

CREATE TABLE Tue4_SERVER (
                SRV_ID VARCHAR(32) NOT NULL,
                SRV_NAME VARCHAR(250) NOT NULL,
                SRV_STATUS VARCHAR(5) DEFAULT 'OFF' NOT NULL,
                SRV_IP VARCHAR(150) NOT NULL,
                SRV_DESCRIPTION VARCHAR(2048),
                SRV_ALIAS VARCHAR(150) NOT NULL,
                SRV_LAST_CHECK TIMESTAMP,
                SRV_UE4_PORT VARCHAR(5),
                SRV_ZMQ_PORT VARCHAR(5),
                SRV_MAX_PLAYERS INTEGER DEFAULT 10 NOT NULL,
                SRV_RUNNING_VERSION VARCHAR(25),
                SRV_USE_CYCLE BIT DEFAULT 0 NOT NULL,
                SRV_SANCTIONED BIT DEFAULT 0 NOT NULL,
                SRV_VISIBLE BIT DEFAULT 0 NOT NULL,
                SRV_PIL_ID VARCHAR(32),
                SRV_LAST_USE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                SRV_MCH_ID VARCHAR(32),
                SRV_DEVELOPMENT BIT DEFAULT 0 NOT NULL,
                SRV_USE_CUSTOM_CYCLE BIT DEFAULT 0 NOT NULL,
                SRV_CHA_ID VARCHAR(32),
                SRV_MAX_BOTS INTEGER DEFAULT 5 NOT NULL,
                SRV_MATCH_TIME INTEGER DEFAULT 30 NOT NULL,
                CONSTRAINT Tue4_SERVER_PK PRIMARY KEY (SRV_ID)
);


CREATE INDEX Kue4_SRV_PIL_FK
 ON Tue4_SERVER
 ( SRV_PIL_ID ASC );

CREATE INDEX Kue4_MCH_SRV_FK
 ON Tue4_SERVER
 ( SRV_MCH_ID ASC );

CREATE INDEX Kue4_SRV_CHA_FK_IDX
 ON Tue4_SERVER
 ( SRV_CHA_ID ASC );

CREATE TABLE Tue4_PILOT (
                PIL_ID VARCHAR(32) NOT NULL,
                PIL_CALLSIGN VARCHAR(250) NOT NULL,
                PIL_USU_ID INTEGER NOT NULL,
                PIL_SRV_ID VARCHAR(32),
                PIL_TOKEN VARCHAR(32),
                PIL_LAST_PING TIMESTAMP,
                PIL_LAST_IP VARCHAR(150),
                PIL_LAST_VERSION VARCHAR(25),
                PIL_LAST_LOGIN TIMESTAMP,
                PIL_DISABLE_CHAT BIT DEFAULT 0 NOT NULL,
                PIL_RMBR_TOKEN VARCHAR(32),
                PIL_UTH_ID VARCHAR(32),
                PIL_DISABLE_REQUESTS BIT DEFAULT 0 NOT NULL,
                PIL_LEAVE_REASON VARCHAR(150),
                PIL_LEAVE_DATE TIMESTAMP,
                PIL_OFF_LIMITS BIT DEFAULT 0 NOT NULL,
                PIL_DEFAULT_SCHEME VARCHAR(1024),
                PIL_USE_CUSTOM_SCHEME BIT DEFAULT 0 NOT NULL,
                CONSTRAINT Tue4_PILOT_PK PRIMARY KEY (PIL_ID)
);


CREATE INDEX Kue4_PIL_SRV_FK
 ON Tue4_PILOT
 ( PIL_SRV_ID ASC );

CREATE INDEX Kue4_PIL_UTH_ID
 ON Tue4_PILOT
 ( PIL_UTH_ID ASC );

CREATE INDEX Iue4_PIL_PK
 ON Tue4_PILOT
 ( PIL_ID ASC );

CREATE TABLE Tue4_REGISTRATION (
                REG_PIL_ID VARCHAR(32) NOT NULL,
                REG_CHA_ID VARCHAR(32) NOT NULL,
                REG_DATE_REGISTERED TIMESTAMP NOT NULL,
                REG_SCORE BIGINT,
                CONSTRAINT Tue4_REGISTRATION_PK PRIMARY KEY (REG_PIL_ID, REG_CHA_ID)
);


CREATE INDEX Kue4_CHA_REG_FK
 ON Tue4_REGISTRATION
 ( REG_CHA_ID ASC );

CREATE TABLE Tue4_PAINT_SCHEME (
                PIS_ID VARCHAR(32) NOT NULL,
                PIS_PIL_ID VARCHAR(32) NOT NULL,
                PIS_NAME VARCHAR(100) NOT NULL,
                PIS_SCHEME VARCHAR(1024) NOT NULL,
                CONSTRAINT Tue4_PAINT_SCHEME_PK PRIMARY KEY (PIS_ID)
);


CREATE INDEX Kue4_PIS_PIL_FK
 ON Tue4_PAINT_SCHEME
 ( PIS_PIL_ID ASC );

CREATE TABLE Tue4_CONFIG_ITEM (
                CFI_ID VARCHAR(150) NOT NULL,
                CFI_VALUE VARCHAR(100) NOT NULL,
                CFI_PIL_ID VARCHAR(32) NOT NULL,
                CONSTRAINT Tue4_CONFIG_ITEM_PK PRIMARY KEY (CFI_ID)
);


CREATE INDEX Kue4_CFI_PIL_FK
 ON Tue4_CONFIG_ITEM
 ( CFI_PIL_ID ASC );

CREATE TABLE Tue4_ALLEGIANCE (
                ALI_PIL_ID VARCHAR(32) NOT NULL,
                ALI_STA_ID VARCHAR(32) NOT NULL,
                ALI_DATE_INIT TIMESTAMP NOT NULL,
                ALI_DATE_END TIMESTAMP NOT NULL,
                ALI_RANK_NUMBER INTEGER NOT NULL,
                ALI_RANK VARCHAR(200) NOT NULL,
                CONSTRAINT Tue4_ALLEGIANCE_PK PRIMARY KEY (ALI_PIL_ID, ALI_STA_ID)
);


CREATE INDEX Kue4_STA_ALI_FK
 ON Tue4_ALLEGIANCE
 ( ALI_STA_ID ASC );

CREATE TABLE Tue4_GEAR_INSTANCE (
                GEI_ID VARCHAR(32) NOT NULL,
                GEI_GEM_ID VARCHAR(32) NOT NULL,
                GEI_PIL_ID VARCHAR(32) NOT NULL,
                GEI_NAME VARCHAR(250) NOT NULL,
                GEI_FLG_CUSTOM_NAME CHAR(1) DEFAULT 'N' NOT NULL,
                GEI_BLU_ENGINE VARCHAR(150),
                GEI_BLU_FUEL_TANK VARCHAR(150),
                GEI_BLU_PYLON_RIGHT VARCHAR(150),
                GEI_BLU_PYLON_LEFT VARCHAR(150),
                GEI_BLU_HEAD VARCHAR(150),
                GEI_BLU_HIP VARCHAR(150),
                GEI_BLU_TORSO VARCHAR(150),
                GEI_BLU_FOOT_RIGHT VARCHAR(150),
                GEI_BLU_FOOT_LEFT VARCHAR(150),
                GEI_BLU_UPPER_LEG_RIGHT VARCHAR(150),
                GEI_BLU_UPPER_LEG_LEFT VARCHAR(150),
                GEI_BLU_LOWER_LEG_RIGHT VARCHAR(150),
                GEI_BLU_LOWER_LEG_LEFT VARCHAR(150),
                GEI_BLU_HAND_RIGHT VARCHAR(150),
                GEI_BLU_HAND_LEFT VARCHAR(150),
                GEI_BLU_LOWER_ARM_RIGHT VARCHAR(150),
                GEI_BLU_LOWER_ARM_LEFT VARCHAR(150),
                GEI_BLU_UPPER_ARM_RIGHT VARCHAR(150),
                GEI_BLU_UPPER_ARM_LEFT VARCHAR(150),
                GEI_BLU_SHOULDER_RIGHT VARCHAR(150),
                GEI_BLU_SHOULDER_LEFT VARCHAR(150),
                GEI_DEFAULT_SCHEME VARCHAR(1024),
                GEI_USE_CUSTOM_SCHEME BIT DEFAULT 0,
                GEI_GES_ENGINE VARCHAR(32),
                GEI_GES_FUEL_TANK VARCHAR(32),
                GEI_GES_PYLON_RIGHT VARCHAR(32),
                GEI_GES_PYLON_LEFT VARCHAR(32),
                GEI_GES_FOOT_RIGHT VARCHAR(32),
                GEI_GES_FOOT_LEFT VARCHAR(32),
                GEI_GES_UPPER_LEG_RIGHT VARCHAR(32),
                GEI_GES_UPPER_LEG_LEFT VARCHAR(32),
                GEI_GES_LOWER_LEG_RIGHT VARCHAR(32),
                GEI_GES_LOWER_LEG_LEFT VARCHAR(32),
                GEI_GES_HAND_RIGHT VARCHAR(32),
                GEI_GES_HAND_LEFT VARCHAR(32),
                GEI_GES_LOWER_ARM_RIGHT VARCHAR(32),
                GEI_GES_LOWER_ARM_LEFT VARCHAR(32),
                GEI_GES_UPPER_ARM_RIGHT VARCHAR(32),
                GEI_GES_UPPER_ARM_LEFT VARCHAR(32),
                GEI_GES_SHOULDER_RIGHT VARCHAR(32),
                GEI_GES_SHOULDER_LEFT VARCHAR(32),
                GEI_GES_HEAD VARCHAR(32),
                GEI_GES_HIP VARCHAR(32),
                GEI_GES_TORSO VARCHAR(32),
                CONSTRAINT Tue4_GEAR_INSTANCE_PK PRIMARY KEY (GEI_ID)
);


CREATE INDEX Kue4_GEM_GEI_FK
 ON Tue4_GEAR_INSTANCE
 ( GEI_GEM_ID ASC );

CREATE INDEX Kue4_PIL_GEI_FK
 ON Tue4_GEAR_INSTANCE
 ( GEI_PIL_ID ASC );

CREATE INDEX Kue4_GEI_GEIS_ENGINE_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_ENGINE ASC );

CREATE INDEX Kue4_GEI_GEIS_FUEL_TANK_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_FUEL_TANK ASC );

CREATE INDEX Kue4_GEI_GEIS_PYLON_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_PYLON_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_PYLON_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_PYLON_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_FOOT_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_FOOT_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_FOOT_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_FOOT_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_UPPER_LEG_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_UPPER_LEG_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_UPPER_LEG_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_UPPER_LEG_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_LOWER_LEG_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_LOWER_LEG_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_LOWER_LEG_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_LOWER_LEG_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_HAND_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_HAND_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_HAND_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_HAND_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_LOWER_ARM_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_LOWER_ARM_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_LOWER_ARM_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_LOWER_ARM_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_UPPER_ARM_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_UPPER_ARM_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_UPPER_ARM_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_UPPER_ARM_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_SHOULDER_RIGHT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_SHOULDER_RIGHT ASC );

CREATE INDEX Kue4_GEI_GEIS_SHOULDER_LEFT_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_SHOULDER_LEFT ASC );

CREATE INDEX Kue4_GEI_GEIS_HEAD_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_HEAD ASC );

CREATE INDEX Kue4_GEI_GEIS_HIP_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_HIP ASC );

CREATE INDEX Kue4_GEI_GEIS_TORSO_FK_IDX
 ON Tue4_GEAR_INSTANCE
 ( GEI_GES_TORSO ASC );

CREATE TABLE Tue4_INVENTORY_INSTANCE (
                INI_ID VARCHAR(32) NOT NULL,
                INI_INO_ID VARCHAR(32) NOT NULL,
                INI_PIL_ID VARCHAR(32) NOT NULL,
                INI_GEI_ID VARCHAR(32) NOT NULL,
                INI_INL_ID VARCHAR(32) NOT NULL,
                CONSTRAINT Tue4_INVENTORY_INSTANCE_PK PRIMARY KEY (INI_ID)
);


CREATE INDEX Kue4_INI_INL_FK
 ON Tue4_INVENTORY_INSTANCE
 ( INI_INL_ID ASC );

CREATE INDEX Kue4_INI_INO_FK
 ON Tue4_INVENTORY_INSTANCE
 ( INI_INO_ID ASC );

CREATE INDEX Kue4_INI_PIL_FK
 ON Tue4_INVENTORY_INSTANCE
 ( INI_PIL_ID ASC );

CREATE INDEX Kue4_INI_GEI_FK
 ON Tue4_INVENTORY_INSTANCE
 ( INI_GEI_ID ASC );

CREATE TABLE Tue4_MATCH (
                MCH_ID VARCHAR(32) NOT NULL,
                MCH_MAP_ID VARCHAR(150) NOT NULL,
                MCH_CHA_ID VARCHAR(32),
                MCH_DATE_INIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                MCH_DATE_END TIMESTAMP,
                MCH_GAM_ID VARCHAR(150) NOT NULL,
                MCH_WINNER_TEAM INTEGER,
                MCH_SRV_ID VARCHAR(32) NOT NULL,
                MCH_DATE_START TIMESTAMP,
                MCH_SANCTIONED BIT DEFAULT 1 NOT NULL,
                MCH_BOTS_AMOUNT INTEGER DEFAULT 0 NOT NULL,
                MCH_MATCH_TIME INTEGER,
                CONSTRAINT Tue4_MATCH_PK PRIMARY KEY (MCH_ID)
);


CREATE INDEX Kue4_MAP_MCH_FK
 ON Tue4_MATCH
 ( MCH_MAP_ID ASC );

CREATE INDEX Kue4_SRV_MCH_FK
 ON Tue4_MATCH
 ( MCH_SRV_ID ASC );

CREATE INDEX Iue4_MCH_DATE
 ON Tue4_MATCH
 ( MCH_DATE_INIT ASC );

CREATE INDEX Kue4_MCH_CHA_FK_IDX
 ON Tue4_MATCH
 ( MCH_CHA_ID ASC );

CREATE INDEX Kue4_GAM_MCH_FK
 ON Tue4_MATCH
 ( MCH_GAM_ID ASC );

CREATE TABLE Tue4_PARTICIPATION (
                PAR_ID VARCHAR(32) NOT NULL,
                PAR_PIL_ID VARCHAR(32) NOT NULL,
                PAR_MCH_ID VARCHAR(32) NOT NULL,
                PAR_DATE_END TIMESTAMP,
                PAR_DATE_INIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                PAR_TEAM INTEGER,
                PAR_SCORE BIGINT,
                PAR_DEATH_RANKING INTEGER,
                PAR_KILLS INTEGER,
                PAR_DEATHS INTEGER,
                PAR_DATE_SUMMARY TIMESTAMP,
                PAR_FLG_SURVIVED BIT DEFAULT 1 NOT NULL,
                CONSTRAINT Tue4_PARTICIPATION_PK PRIMARY KEY (PAR_ID)
);


CREATE INDEX Kue4_PIL_PAR_FK
 ON Tue4_PARTICIPATION
 ( PAR_PIL_ID ASC );

CREATE INDEX Kue4_MCH_PAR_FK
 ON Tue4_PARTICIPATION
 ( PAR_MCH_ID ASC );

CREATE TABLE Tue4_MATCH_EVENT (
                MEV_ID VARCHAR(32) NOT NULL,
                MEV_GEI_ID_TARGET VARCHAR(32),
                MEV_GEI_ID_SOURCE VARCHAR(32),
                MEV_TYPE VARCHAR(75) NOT NULL,
                MEV_VALUE BIGINT,
                MEV_PAR_ID_SOURCE VARCHAR(32),
                MEV_PAR_ID_TARGET VARCHAR(32),
                MEV_TXT_VALUE VARCHAR(150),
                MEV_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT Tue4_MATCH_EVENT_PK PRIMARY KEY (MEV_ID)
);


CREATE INDEX Kue4_GEI_MEV_SOURCE_FK
 ON Tue4_MATCH_EVENT
 ( MEV_GEI_ID_SOURCE ASC );

CREATE INDEX Kue4_GEI_MEV_TARGET_FK
 ON Tue4_MATCH_EVENT
 ( MEV_GEI_ID_TARGET ASC );

CREATE INDEX Kue4_PAR_MEV_SOURCE_FK
 ON Tue4_MATCH_EVENT
 ( MEV_PAR_ID_SOURCE ASC );

CREATE INDEX Kue4_PAR_MEV_TARGET_FK
 ON Tue4_MATCH_EVENT
 ( MEV_PAR_ID_TARGET ASC );

CREATE INDEX Iue4_MEV_TYPE
 ON Tue4_MATCH_EVENT
 ( MEV_TYPE ASC );

CREATE TABLE Tue4_RANKING (
                RNK_ID VARCHAR(32) NOT NULL,
                RNK_PIL_ID VARCHAR(32) NOT NULL,
                RNK_SCORE INTEGER NOT NULL,
                RNK_LEB_ID VARCHAR(32) NOT NULL,
                CONSTRAINT Tue4_RANKING_PK PRIMARY KEY (RNK_ID)
);


CREATE INDEX Kue4_LEB_RNK_FK
 ON Tue4_RANKING
 ( RNK_LEB_ID ASC );

CREATE INDEX Kue4_PIL_RNK_FK
 ON Tue4_RANKING
 ( RNK_PIL_ID ASC );

CREATE TABLE Tue4_RELATIONSHIP (
                REL_PIL_ID_SOURCE VARCHAR(32) NOT NULL,
                REL_PIL_ID_TARGET VARCHAR(32) NOT NULL,
                REL_LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                REL_STATUS VARCHAR(150) NOT NULL,
                CONSTRAINT Tue4_RELATIONSHIP_PK PRIMARY KEY (REL_PIL_ID_SOURCE, REL_PIL_ID_TARGET)
);


CREATE INDEX Kue4_REL_PIL__TGT_FK
 ON Tue4_RELATIONSHIP
 ( REL_PIL_ID_TARGET ASC );

ALTER TABLE Tue4_UI_THEME_ATTRIBUTE ADD CONSTRAINT Kue4_UTA_AUT_FK
FOREIGN KEY (UTA_UAT_ID)
REFERENCES Tue4_UI_ATTRIBUTE (UAT_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_RANKING ADD CONSTRAINT Kue4_LEB_RNK_FK
FOREIGN KEY (RNK_LEB_ID)
REFERENCES Tue4_LEADERBOARD (LEB_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_ALLEGIANCE ADD CONSTRAINT Kue4_STA_ALI_FK
FOREIGN KEY (ALI_STA_ID)
REFERENCES Tue4_STABLE (STA_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_INVENTORY_INSTANCE ADD CONSTRAINT Kue4_INI_INL_FK
FOREIGN KEY (INI_INL_ID)
REFERENCES Tue4_INVENTORY_LOCATION (INL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH ADD CONSTRAINT Kue4_GAM_MCH_FK
FOREIGN KEY (MCH_GAM_ID)
REFERENCES Tue4_GAME_MODE (GAM_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_INVENTORY_INSTANCE ADD CONSTRAINT Kue4_INI_INO_FK
FOREIGN KEY (INI_INO_ID)
REFERENCES Tue4_INVENTORY_OBJECT (INO_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_PILOT ADD CONSTRAINT Kue4_PIL_UTH_ID
FOREIGN KEY (PIL_UTH_ID)
REFERENCES Tue4_UI_THEME (UTH_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_UI_THEME_ATTRIBUTE ADD CONSTRAINT Kue4_UTA_UTH_FK
FOREIGN KEY (UTA_UTH_ID)
REFERENCES Tue4_UI_THEME (UTH_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_SERVER ADD CONSTRAINT Kue4_SRV_CHA_FK
FOREIGN KEY (SRV_CHA_ID)
REFERENCES Tue4_CHAMPIONSHIP (CHA_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH ADD CONSTRAINT Kue4_MCH_CHA_FK
FOREIGN KEY (MCH_CHA_ID)
REFERENCES Tue4_CHAMPIONSHIP (CHA_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_REGISTRATION ADD CONSTRAINT Kue4_CHA_REG_FK
FOREIGN KEY (REG_CHA_ID)
REFERENCES Tue4_CHAMPIONSHIP (CHA_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH ADD CONSTRAINT Kue4_MAP_MCH_FK
FOREIGN KEY (MCH_MAP_ID)
REFERENCES Tue4_MAP (MAP_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_SECTION_CONFIGURATION ADD CONSTRAINT Kue4_GSC_GES_ID_FK
FOREIGN KEY (GSC_GES_ID)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GEIS_ENGINE_FK
FOREIGN KEY (GEI_GES_ENGINE)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GEIS_FOOT_LEFT_FK
FOREIGN KEY (GEI_GES_FOOT_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_FOOT_RIGHT_FK
FOREIGN KEY (GEI_GES_FOOT_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_FUEL_TANK_FK
FOREIGN KEY (GEI_GES_FUEL_TANK)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_HAND_LEFT_FK
FOREIGN KEY (GEI_GES_HAND_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_HAND_RIGHT_FK
FOREIGN KEY (GEI_GES_HAND_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_HEAD_FK
FOREIGN KEY (GEI_GES_HEAD)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_HIP_FK
FOREIGN KEY (GEI_GES_HIP)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_LOWER_ARM_LEFT_FK
FOREIGN KEY (GEI_GES_LOWER_ARM_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_LOWER_ARM_RIGHT_FK
FOREIGN KEY (GEI_GES_LOWER_ARM_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_LOWER_LEG_LEFT_FK
FOREIGN KEY (GEI_GES_LOWER_LEG_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_LOWER_LEG_RIGHT_FK
FOREIGN KEY (GEI_GES_LOWER_LEG_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_PYLON_LEFT_FK
FOREIGN KEY (GEI_GES_PYLON_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_PYLON_RIGHT_FK
FOREIGN KEY (GEI_GES_PYLON_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_SHOULDER_LEFT_FK
FOREIGN KEY (GEI_GES_SHOULDER_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_SHOULDER_RIGHT_FK
FOREIGN KEY (GEI_GES_SHOULDER_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_TORSO_FK
FOREIGN KEY (GEI_GES_TORSO)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_UPPER_ARM_LEFT_FK
FOREIGN KEY (GEI_GES_UPPER_ARM_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_UPPER_ARM_RIGHT_FK
FOREIGN KEY (GEI_GES_UPPER_ARM_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_UPPER_LEG_LEFT_FK
FOREIGN KEY (GEI_GES_UPPER_LEG_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEI_GES_UPPER_LEG_RIGHT_FK
FOREIGN KEY (GEI_GES_UPPER_LEG_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_ENGINE_FK
FOREIGN KEY (GEM_GES_ENGINE)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_FOOT_LEFT_FK
FOREIGN KEY (GEM_GES_FOOT_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_FOOT_RIGHT_FK
FOREIGN KEY (GEM_GES_FOOT_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_FUEL_TANK_FK
FOREIGN KEY (GEM_GES_FUEL_TANK)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_HAND_LEFT_FK
FOREIGN KEY (GEM_GES_HAND_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_HAND_RIGHT_FK
FOREIGN KEY (GEM_GES_HAND_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_HEAD_FK
FOREIGN KEY (GEM_GES_HEAD)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_HIP_FK
FOREIGN KEY (GEM_GES_HIP)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_LOWER_ARM_LEFT_FK
FOREIGN KEY (GEM_GES_LOWER_ARM_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_LOWER_ARM_RIGHT_FK
FOREIGN KEY (GEM_GES_LOWER_ARM_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_LOWER_LEG_LEFT_FK
FOREIGN KEY (GEM_GES_LOWER_LEG_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_LOWER_LEG_RIGHT_FK
FOREIGN KEY (GEM_GES_LOWER_LEG_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_PYLON_LEFT_FK
FOREIGN KEY (GEM_GES_PYLON_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_PYLON_RIGHT_FK
FOREIGN KEY (GEM_GES_PYLON_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_SHOULDER_LEFT_FK
FOREIGN KEY (GEM_GES_SHOULDER_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_SHOULDER_RIGHT_FK
FOREIGN KEY (GEM_GES_SHOULDER_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_TORSO_FK
FOREIGN KEY (GEM_GES_TORSO)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_UPPER_ARM_LEFT_FK
FOREIGN KEY (GEM_GES_UPPER_ARM_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_UPPER_ARM_RIGHT_FK
FOREIGN KEY (GEM_GES_UPPER_ARM_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_UPPER_LEG_LEFT_FK
FOREIGN KEY (GEM_GES_UPPER_LEG_LEFT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_MODEL ADD CONSTRAINT Kue4_GEM_GES_UPPER_LEG_RIGHT_FK
FOREIGN KEY (GEM_GES_UPPER_LEG_RIGHT)
REFERENCES Tue4_GEAR_SECTION (GES_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_GEM_GEI_FK
FOREIGN KEY (GEI_GEM_ID)
REFERENCES Tue4_GEAR_MODEL (GEM_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH ADD CONSTRAINT Kue4_SRV_MCH_FK
FOREIGN KEY (MCH_SRV_ID)
REFERENCES Tue4_SERVER (SRV_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_PILOT ADD CONSTRAINT Kue4_PIL_SRV_FK
FOREIGN KEY (PIL_SRV_ID)
REFERENCES Tue4_SERVER (SRV_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_PARTICIPATION ADD CONSTRAINT Kue4_PIL_PAR_FK
FOREIGN KEY (PAR_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_RANKING ADD CONSTRAINT Kue4_PIL_RNK_FK
FOREIGN KEY (RNK_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_RELATIONSHIP ADD CONSTRAINT Kue4_REL_PIL__SRC_FK
FOREIGN KEY (REL_PIL_ID_SOURCE)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_RELATIONSHIP ADD CONSTRAINT Kue4_REL_PIL__TGT_FK
FOREIGN KEY (REL_PIL_ID_TARGET)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_SERVER ADD CONSTRAINT Kue4_SRV_PIL_FK
FOREIGN KEY (SRV_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_GEAR_INSTANCE ADD CONSTRAINT Kue4_PIL_GEI_FK
FOREIGN KEY (GEI_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_ALLEGIANCE ADD CONSTRAINT Kue4_PIL_ALI_FK
FOREIGN KEY (ALI_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_CONFIG_ITEM ADD CONSTRAINT Kue4_CFI_PIL_FK
FOREIGN KEY (CFI_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_INVENTORY_INSTANCE ADD CONSTRAINT Kue4_INI_PIL_FK
FOREIGN KEY (INI_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_PAINT_SCHEME ADD CONSTRAINT Kue4_PIS_PIL_FK
FOREIGN KEY (PIS_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_REGISTRATION ADD CONSTRAINT Kue4_PIL_REG_FK
FOREIGN KEY (REG_PIL_ID)
REFERENCES Tue4_PILOT (PIL_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH_EVENT ADD CONSTRAINT Kue4_GEI_MEV_SOURCE_FK
FOREIGN KEY (MEV_GEI_ID_SOURCE)
REFERENCES Tue4_GEAR_INSTANCE (GEI_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH_EVENT ADD CONSTRAINT Kue4_GEI_MEV_TARGET_FK
FOREIGN KEY (MEV_GEI_ID_TARGET)
REFERENCES Tue4_GEAR_INSTANCE (GEI_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_INVENTORY_INSTANCE ADD CONSTRAINT Kue4_INI_GEI_FK
FOREIGN KEY (INI_GEI_ID)
REFERENCES Tue4_GEAR_INSTANCE (GEI_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_PARTICIPATION ADD CONSTRAINT Kue4_MCH_PAR_FK
FOREIGN KEY (PAR_MCH_ID)
REFERENCES Tue4_MATCH (MCH_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_SERVER ADD CONSTRAINT Kue4_MCH_SRV_FK
FOREIGN KEY (SRV_MCH_ID)
REFERENCES Tue4_MATCH (MCH_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH_EVENT ADD CONSTRAINT Kue4_PAR_MEV_SOURCE_FK
FOREIGN KEY (MEV_PAR_ID_SOURCE)
REFERENCES Tue4_PARTICIPATION (PAR_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE Tue4_MATCH_EVENT ADD CONSTRAINT Kue4_PAR_MEV_TARGET_FK
FOREIGN KEY (MEV_PAR_ID_TARGET)
REFERENCES Tue4_PARTICIPATION (PAR_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.tue4_match_session
(
  ms_id uuid primary key default uuid_generate_v4(),
  ms_name text,
  ms_map_id text,
  ms_map_mode text,
  ms_create_date timestamp with time zone,
  ms_game_start_date timestamp with time zone,
  ms_game_end_date timestamp with time zone,
  ms_complete_date timestamp with time zone,
  ms_active boolean,
  ms_state integer,
  ms_srv_id text,
  ms_host_id text,
  ms_competitive boolean,
  ms_competition_id text,
  ms_motd text,
  ms_version text,
  ms_time_of_day integer,
  ms_weather_mode integer,
  ms_players_limit integer,
  ms_bot_enabled boolean,
  ms_target_bot_count integer,
  ms_bot_count_high integer,
  ms_bot_count_low integer,
  ms_time_limit bigint,
  ms_score_limit bigint,
  ms_region_code text,
  CONSTRAINT match_session_host_fk FOREIGN KEY (ms_host_id)
      REFERENCES public.tue4_pilot (pil_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT match_session_map_fk FOREIGN KEY (ms_map_id)
      REFERENCES public.tue4_map (map_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT match_session_map_mode_fk FOREIGN KEY (ms_map_mode)
      REFERENCES public.tue4_mapmode (mam_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT match_session_srv_fk FOREIGN KEY (ms_srv_id)
      REFERENCES public.tue4_server (srv_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.tue4_match_session
  OWNER TO postgres;

CREATE TABLE public.tue4_match_session_participant
(
  msp_pilot_id text NOT NULL,
  msp_ms_id uuid NOT NULL,
  msp_user_index integer NOT NULL,
  msp_active boolean NOT NULL,
  CONSTRAINT tue4_match_session_participant_pkey PRIMARY KEY (msp_pilot_id, msp_ms_id),
  CONSTRAINT match_session_fk FOREIGN KEY (msp_ms_id)
      REFERENCES public.tue4_match_session (ms_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT pilot_id_fk FOREIGN KEY (msp_pilot_id)
      REFERENCES public.tue4_pilot (pil_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.tue4_match_session_participant
  OWNER TO postgres;

CREATE TABLE public.tue4_message
(
  msg_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  msg_sender text,
  msg_recipient text,
  msg_type integer,
  msg_time timestamp with time zone,
  msg_expiration real,
  msg_payload text,
  msg_delivered boolean,
  CONSTRAINT message_pk PRIMARY KEY (msg_id),
  CONSTRAINT fk_recipient FOREIGN KEY (msg_recipient)
      REFERENCES public.tue4_pilot (pil_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_sender FOREIGN KEY (msg_sender)
      REFERENCES public.tue4_pilot (pil_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.tue4_message
  OWNER TO postgres;