/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.LoreGearsRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4LoreGears extends TableImpl<LoreGearsRecord> {

    private static final long serialVersionUID = -275106831;

    /**
     * The reference instance of <code>tue4_lore_gears</code>
     */
    public static final Tue4LoreGears LORE_GEARS = new Tue4LoreGears();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoreGearsRecord> getRecordType() {
        return LoreGearsRecord.class;
    }

    /**
     * The column <code>tue4_lore_gears.lge_id</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_ID = createField("lge_id", org.jooq.impl.SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_factions</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_FACTIONS = createField("lge_factions", org.jooq.impl.SQLDataType.VARCHAR(255)
        .nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_name</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_NAME = createField("lge_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this,
        "");

    /**
     * The column <code>tue4_lore_gears.lge_gem_id</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_GEM_ID = createField("lge_gem_id", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_store_order_id</code>.
     */
    public final TableField<LoreGearsRecord, Integer> LGE_STORE_ORDER_ID = createField("lge_store_order_id", org.jooq.impl.SQLDataType.INTEGER, this,
        "");

    /**
     * The column <code>tue4_lore_gears.lge_pledge_id</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_PLEDGE_ID = createField("lge_pledge_id", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_class</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_CLASS = createField("lge_class", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_gears.lge_gear_desc</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_GEAR_DESC = createField("lge_gear_desc",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_core</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_CORE = createField("lge_core", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this,
        "");

    /**
     * The column <code>tue4_lore_gears.lge_backer</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_BACKER = createField("lge_backer", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_gears.lge_engine_heavy_mount_left</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_ENGINE_HEAVY_MOUNT_LEFT = createField("lge_engine_heavy_mount_left",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_engine_heavy_mount_right</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_ENGINE_HEAVY_MOUNT_RIGHT = createField("lge_engine_heavy_mount_right",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_fuel_tank_storage</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_FUEL_TANK_STORAGE = createField("lge_fuel_tank_storage",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_left_collar_mount</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_LEFT_COLLAR_MOUNT = createField("lge_left_collar_mount",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_right_collar_mount</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_RIGHT_COLLAR_MOUNT = createField("lge_right_collar_mount", org.jooq.impl.SQLDataType
        .VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_upper_leg_out_left</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_UPPER_LEG_OUT_LEFT = createField("lge_upper_leg_out_left", org.jooq.impl.SQLDataType
        .VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.lge_upper_leg_out_right</code>.
     */
    public final TableField<LoreGearsRecord, String> LGE_UPPER_LEG_OUT_RIGHT = createField("lge_upper_leg_out_right", org.jooq.impl.SQLDataType
        .VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_gears.created_at</code>.
     */
    public final TableField<LoreGearsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tue4_lore_gears.updated_at</code>.
     */
    public final TableField<LoreGearsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tue4_lore_gears</code> table reference
     */
    public Tue4LoreGears() {
        this(DSL.name("tue4_lore_gears"), null);
    }

    /**
     * Create an aliased <code>tue4_lore_gears</code> table reference
     */
    public Tue4LoreGears(String alias) {
        this(DSL.name(alias), LORE_GEARS);
    }

    /**
     * Create an aliased <code>tue4_lore_gears</code> table reference
     */
    public Tue4LoreGears(Name alias) {
        this(alias, LORE_GEARS);
    }

    private Tue4LoreGears(Name alias, Table<LoreGearsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4LoreGears(Name alias, Table<LoreGearsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LORE_GEARS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LoreGearsRecord> getPrimaryKey() {
        return Keys.LORE_GEARS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LoreGearsRecord>> getKeys() {
        return Arrays.<UniqueKey<LoreGearsRecord>>asList(Keys.LORE_GEARS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreGears as(String alias) {
        return new Tue4LoreGears(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreGears as(Name alias) {
        return new Tue4LoreGears(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreGears rename(String name) {
        return new Tue4LoreGears(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreGears rename(Name name) {
        return new Tue4LoreGears(name, null);
    }
}
