/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.MatchSessionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4MatchSession extends TableImpl<MatchSessionRecord> {

    private static final long serialVersionUID = 1183737250;

    /**
     * The reference instance of <code>tue4_match_session</code>
     */
    public static final Tue4MatchSession MATCH_SESSION = new Tue4MatchSession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MatchSessionRecord> getRecordType() {
        return MatchSessionRecord.class;
    }

    /**
     * The column <code>tue4_match_session.ms_id</code>.
     */
    public final TableField<MatchSessionRecord, UUID> MS_ID = createField("ms_id",
        org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)),
        this, "");

    /**
     * The column <code>tue4_match_session.ms_name</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_NAME = createField("ms_name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_map_id</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_MAP_ID = createField("ms_map_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_map_mode</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_MAP_MODE = createField("ms_map_mode", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_create_date</code>.
     */
    public final TableField<MatchSessionRecord, OffsetDateTime> MS_CREATE_DATE = createField("ms_create_date",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>tue4_match_session.ms_game_start_date</code>.
     */
    public final TableField<MatchSessionRecord, OffsetDateTime> MS_GAME_START_DATE = createField("ms_game_start_date",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>tue4_match_session.ms_game_end_date</code>.
     */
    public final TableField<MatchSessionRecord, OffsetDateTime> MS_GAME_END_DATE = createField("ms_game_end_date",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>tue4_match_session.ms_complete_date</code>.
     */
    public final TableField<MatchSessionRecord, OffsetDateTime> MS_COMPLETE_DATE = createField("ms_complete_date",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>tue4_match_session.ms_active</code>.
     */
    public final TableField<MatchSessionRecord, Boolean> MS_ACTIVE = createField("ms_active", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>tue4_match_session.ms_state</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_STATE = createField("ms_state", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_match_session.ms_srv_id</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_SRV_ID = createField("ms_srv_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_host_id</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_HOST_ID = createField("ms_host_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_competitive</code>.
     */
    public final TableField<MatchSessionRecord, Boolean> MS_COMPETITIVE = createField("ms_competitive", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>tue4_match_session.ms_competition_id</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_COMPETITION_ID =
        createField("ms_competition_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_motd</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_MOTD = createField("ms_motd", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_version</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_VERSION = createField("ms_version", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match_session.ms_time_of_day</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_TIME_OF_DAY = createField("ms_time_of_day", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_match_session.ms_weather_mode</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_WEATHER_MODE =
        createField("ms_weather_mode", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_match_session.ms_players_limit</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_PLAYERS_LIMIT = createField("ms_players_limit", org.jooq.impl.SQLDataType.INTEGER, this,
        "");

    /**
     * The column <code>tue4_match_session.ms_bot_enabled</code>.
     */
    public final TableField<MatchSessionRecord, Boolean> MS_BOT_ENABLED = createField("ms_bot_enabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>tue4_match_session.ms_target_bot_count</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_TARGET_BOT_COUNT = createField("ms_target_bot_count", org.jooq.impl.SQLDataType.INTEGER,
        this, "");

    /**
     * The column <code>tue4_match_session.ms_bot_count_high</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_BOT_COUNT_HIGH = createField("ms_bot_count_high", org.jooq.impl.SQLDataType.INTEGER,
        this, "");

    /**
     * The column <code>tue4_match_session.ms_bot_count_low</code>.
     */
    public final TableField<MatchSessionRecord, Integer> MS_BOT_COUNT_LOW = createField("ms_bot_count_low", org.jooq.impl.SQLDataType.INTEGER, this,
        "");

    /**
     * The column <code>tue4_match_session.ms_time_limit</code>.
     */
    public final TableField<MatchSessionRecord, Long> MS_TIME_LIMIT = createField("ms_time_limit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>tue4_match_session.ms_score_limit</code>.
     */
    public final TableField<MatchSessionRecord, Long> MS_SCORE_LIMIT = createField("ms_score_limit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>tue4_match_session.ms_region_code</code>.
     */
    public final TableField<MatchSessionRecord, String> MS_REGION_CODE = createField("ms_region_code", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>tue4_match_session</code> table reference
     */
    public Tue4MatchSession() {
        this(DSL.name("tue4_match_session"), null);
    }

    /**
     * Create an aliased <code>tue4_match_session</code> table reference
     */
    public Tue4MatchSession(String alias) {
        this(DSL.name(alias), MATCH_SESSION);
    }

    /**
     * Create an aliased <code>tue4_match_session</code> table reference
     */
    public Tue4MatchSession(Name alias) {
        this(alias, MATCH_SESSION);
    }

    private Tue4MatchSession(Name alias, Table<MatchSessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4MatchSession(Name alias, Table<MatchSessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MATCH_SESSION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MatchSessionRecord> getPrimaryKey() {
        return Keys.MATCH_SESSION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MatchSessionRecord>> getKeys() {
        return Arrays.<UniqueKey<MatchSessionRecord>>asList(Keys.MATCH_SESSION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MatchSessionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MatchSessionRecord, ?>>asList(Keys.MATCH_SESSION__MATCH_SESSION_MAP_FK,
            Keys.MATCH_SESSION__MATCH_SESSION_MAP_MODE_FK, Keys.MATCH_SESSION__MATCH_SESSION_SRV_FK, Keys.MATCH_SESSION__MATCH_SESSION_HOST_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4MatchSession as(String alias) {
        return new Tue4MatchSession(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4MatchSession as(Name alias) {
        return new Tue4MatchSession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4MatchSession rename(String name) {
        return new Tue4MatchSession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4MatchSession rename(Name name) {
        return new Tue4MatchSession(name, null);
    }
}
