/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.MatchRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4Match extends TableImpl<MatchRecord> {

    private static final long serialVersionUID = 1807865583;

    /**
     * The reference instance of <code>tue4_match</code>
     */
    public static final Tue4Match MATCH = new Tue4Match();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MatchRecord> getRecordType() {
        return MatchRecord.class;
    }

    /**
     * The column <code>tue4_match.mch_id</code>.
     */
    public final TableField<MatchRecord, String> MCH_ID = createField("mch_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_match.mch_map_id</code>.
     */
    public final TableField<MatchRecord, String> MCH_MAP_ID = createField("mch_map_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_match.mch_cha_id</code>.
     */
    public final TableField<MatchRecord, String> MCH_CHA_ID = createField("mch_cha_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_match.mch_date_init</code>.
     */
    public final TableField<MatchRecord, OffsetDateTime> MCH_DATE_INIT = createField("mch_date_init", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE
        .nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>tue4_match.mch_date_end</code>.
     */
    public final TableField<MatchRecord, OffsetDateTime> MCH_DATE_END = createField("mch_date_end", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE,
        this, "");

    /**
     * The column <code>tue4_match.mch_gam_id</code>.
     */
    public final TableField<MatchRecord, String> MCH_GAM_ID = createField("mch_gam_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_match.mch_winner_team</code>.
     */
    public final TableField<MatchRecord, Long> MCH_WINNER_TEAM = createField("mch_winner_team", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>tue4_match.mch_srv_id</code>.
     */
    public final TableField<MatchRecord, String> MCH_SRV_ID = createField("mch_srv_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_match.mch_date_start</code>.
     */
    public final TableField<MatchRecord, OffsetDateTime> MCH_DATE_START = createField("mch_date_start",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>tue4_match.mch_sanctioned</code>.
     */
    public final TableField<MatchRecord, Boolean> MCH_SANCTIONED = createField("mch_sanctioned", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>tue4_match.mch_bots_amount</code>.
     */
    public final TableField<MatchRecord, Long> MCH_BOTS_AMOUNT = createField("mch_bots_amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("(0)::bigint", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>tue4_match.mch_match_time</code>.
     */
    public final TableField<MatchRecord, Long> MCH_MATCH_TIME = createField("mch_match_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>tue4_match.mch_score_limit</code>.
     */
    public final TableField<MatchRecord, Long> MCH_SCORE_LIMIT = createField("mch_score_limit", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>tue4_match</code> table reference
     */
    public Tue4Match() {
        this(DSL.name("tue4_match"), null);
    }

    /**
     * Create an aliased <code>tue4_match</code> table reference
     */
    public Tue4Match(String alias) {
        this(DSL.name(alias), MATCH);
    }

    /**
     * Create an aliased <code>tue4_match</code> table reference
     */
    public Tue4Match(Name alias) {
        this(alias, MATCH);
    }

    private Tue4Match(Name alias, Table<MatchRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4Match(Name alias, Table<MatchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_16722_Iue4_MCH_DATE, Indexes.IDX_16722_Kue4_GAM_MCH_FK, Indexes.IDX_16722_Kue4_MAP_MCH_FK,
            Indexes.IDX_16722_Kue4_MCH_CHA_FK_IDX, Indexes.IDX_16722_Kue4_SRV_MCH_FK, Indexes.MATCH_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MatchRecord> getPrimaryKey() {
        return Keys.MATCH_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MatchRecord>> getKeys() {
        return Arrays.<UniqueKey<MatchRecord>>asList(Keys.MATCH_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Match as(String alias) {
        return new Tue4Match(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Match as(Name alias) {
        return new Tue4Match(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Match rename(String name) {
        return new Tue4Match(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Match rename(Name name) {
        return new Tue4Match(name, null);
    }
}
