/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.InventoryObjectRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4InventoryObject extends TableImpl<InventoryObjectRecord> {

    private static final long serialVersionUID = -557570925;

    /**
     * The reference instance of <code>tue4_inventory_object</code>
     */
    public static final Tue4InventoryObject INVENTORY_OBJECT = new Tue4InventoryObject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryObjectRecord> getRecordType() {
        return InventoryObjectRecord.class;
    }

    /**
     * The column <code>tue4_inventory_object.ino_id</code>.
     */
    public final TableField<InventoryObjectRecord, String> INO_ID = createField("ino_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_inventory_object.ino_name</code>.
     */
    public final TableField<InventoryObjectRecord, String> INO_NAME = createField("ino_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this,
        "");

    /**
     * The column <code>tue4_inventory_object.ino_blu_master</code>.
     */
    public final TableField<InventoryObjectRecord, String> INO_BLU_MASTER = createField("ino_blu_master", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_inventory_object.ino_size</code>.
     */
    public final TableField<InventoryObjectRecord, Long> INO_SIZE = createField("ino_size", org.jooq.impl.SQLDataType.BIGINT.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("(1)::bigint", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>tue4_inventory_object.ino_type</code>.
     */
    public final TableField<InventoryObjectRecord, String> INO_TYPE = createField("ino_type", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>tue4_inventory_object</code> table reference
     */
    public Tue4InventoryObject() {
        this(DSL.name("tue4_inventory_object"), null);
    }

    /**
     * Create an aliased <code>tue4_inventory_object</code> table reference
     */
    public Tue4InventoryObject(String alias) {
        this(DSL.name(alias), INVENTORY_OBJECT);
    }

    /**
     * Create an aliased <code>tue4_inventory_object</code> table reference
     */
    public Tue4InventoryObject(Name alias) {
        this(alias, INVENTORY_OBJECT);
    }

    private Tue4InventoryObject(Name alias, Table<InventoryObjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4InventoryObject(Name alias, Table<InventoryObjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INVENTORY_OBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InventoryObjectRecord> getPrimaryKey() {
        return Keys.INVENTORY_OBJECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InventoryObjectRecord>> getKeys() {
        return Arrays.<UniqueKey<InventoryObjectRecord>>asList(Keys.INVENTORY_OBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4InventoryObject as(String alias) {
        return new Tue4InventoryObject(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4InventoryObject as(Name alias) {
        return new Tue4InventoryObject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4InventoryObject rename(String name) {
        return new Tue4InventoryObject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4InventoryObject rename(Name name) {
        return new Tue4InventoryObject(name, null);
    }
}
