/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.EquipmentAwardedRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4EquipmentAwarded extends TableImpl<EquipmentAwardedRecord> {

    private static final long serialVersionUID = -485317494;

    /**
     * The reference instance of <code>tue4_equipment_awarded</code>
     */
    public static final Tue4EquipmentAwarded EQUIPMENT_AWARDED = new Tue4EquipmentAwarded();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EquipmentAwardedRecord> getRecordType() {
        return EquipmentAwardedRecord.class;
    }

    /**
     * The column <code>tue4_equipment_awarded.eqa_product_id</code>.
     */
    public final TableField<EquipmentAwardedRecord, Long> EQA_PRODUCT_ID = createField("eqa_product_id",
        org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tue4_equipment_awarded.eqa_awarded_leq_id</code>.
     */
    public final TableField<EquipmentAwardedRecord, String> EQA_AWARDED_LEQ_ID = createField("eqa_awarded_leq_id", org.jooq.impl.SQLDataType.CHAR(32)
        .nullable(false), this, "");

    /**
     * The column <code>tue4_equipment_awarded.eqa_quantity</code>.
     */
    public final TableField<EquipmentAwardedRecord, BigDecimal> EQA_QUANTITY = createField("eqa_quantity", org.jooq.impl.SQLDataType.NUMERIC(15, 5)
        .nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>tue4_equipment_awarded.eqa_created_at</code>.
     */
    public final TableField<EquipmentAwardedRecord, OffsetDateTime> EQA_CREATED_AT = createField(
        "eqa_created_at",
        org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(
            org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * Create a <code>tue4_equipment_awarded</code> table reference
     */
    public Tue4EquipmentAwarded() {
        this(DSL.name("tue4_equipment_awarded"), null);
    }

    /**
     * Create an aliased <code>tue4_equipment_awarded</code> table reference
     */
    public Tue4EquipmentAwarded(String alias) {
        this(DSL.name(alias), EQUIPMENT_AWARDED);
    }

    /**
     * Create an aliased <code>tue4_equipment_awarded</code> table reference
     */
    public Tue4EquipmentAwarded(Name alias) {
        this(alias, EQUIPMENT_AWARDED);
    }

    private Tue4EquipmentAwarded(Name alias, Table<EquipmentAwardedRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4EquipmentAwarded(Name alias, Table<EquipmentAwardedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EQUIPMENT_AWARDED_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EquipmentAwardedRecord> getPrimaryKey() {
        return Keys.EQUIPMENT_AWARDED_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EquipmentAwardedRecord>> getKeys() {
        return Arrays.<UniqueKey<EquipmentAwardedRecord>>asList(Keys.EQUIPMENT_AWARDED_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EquipmentAwardedRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EquipmentAwardedRecord, ?>>asList(Keys.EQUIPMENT_AWARDED__Tue4_EQUIPMENT_AWARDED_EQA_AWARDED_LEQ_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4EquipmentAwarded as(String alias) {
        return new Tue4EquipmentAwarded(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4EquipmentAwarded as(Name alias) {
        return new Tue4EquipmentAwarded(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4EquipmentAwarded rename(String name) {
        return new Tue4EquipmentAwarded(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4EquipmentAwarded rename(Name name) {
        return new Tue4EquipmentAwarded(name, null);
    }
}
