/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.UiThemeRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4UiTheme extends TableImpl<UiThemeRecord> {

    private static final long serialVersionUID = 2082644114;

    /**
     * The reference instance of <code>tue4_ui_theme</code>
     */
    public static final Tue4UiTheme UI_THEME = new Tue4UiTheme();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UiThemeRecord> getRecordType() {
        return UiThemeRecord.class;
    }

    /**
     * The column <code>tue4_ui_theme.uth_id</code>.
     */
    public final TableField<UiThemeRecord, String> UTH_ID = createField("uth_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_ui_theme.uth_name</code>.
     */
    public final TableField<UiThemeRecord, String> UTH_NAME = createField("uth_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_ui_theme.uth_description</code>.
     */
    public final TableField<UiThemeRecord, String> UTH_DESCRIPTION = createField("uth_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>tue4_ui_theme</code> table reference
     */
    public Tue4UiTheme() {
        this(DSL.name("tue4_ui_theme"), null);
    }

    /**
     * Create an aliased <code>tue4_ui_theme</code> table reference
     */
    public Tue4UiTheme(String alias) {
        this(DSL.name(alias), UI_THEME);
    }

    /**
     * Create an aliased <code>tue4_ui_theme</code> table reference
     */
    public Tue4UiTheme(Name alias) {
        this(alias, UI_THEME);
    }

    private Tue4UiTheme(Name alias, Table<UiThemeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4UiTheme(Name alias, Table<UiThemeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_16809_Kue4_UTH_NAME_UK, Indexes.UI_THEME_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UiThemeRecord> getPrimaryKey() {
        return Keys.UI_THEME_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UiThemeRecord>> getKeys() {
        return Arrays.<UniqueKey<UiThemeRecord>>asList(Keys.UI_THEME_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4UiTheme as(String alias) {
        return new Tue4UiTheme(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4UiTheme as(Name alias) {
        return new Tue4UiTheme(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4UiTheme rename(String name) {
        return new Tue4UiTheme(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4UiTheme rename(Name name) {
        return new Tue4UiTheme(name, null);
    }
}
