/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.GearSectionConfigurationRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4GearSectionConfiguration extends TableImpl<GearSectionConfigurationRecord> {

    private static final long serialVersionUID = 1835177983;

    /**
     * The reference instance of <code>tue4_gear_section_configuration</code>
     */
    public static final Tue4GearSectionConfiguration GEAR_SECTION_CONFIGURATION = new Tue4GearSectionConfiguration();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GearSectionConfigurationRecord> getRecordType() {
        return GearSectionConfigurationRecord.class;
    }

    /**
     * The column <code>tue4_gear_section_configuration.gsc_id</code>.
     */
    public final TableField<GearSectionConfigurationRecord, String> GSC_ID = createField("gsc_id", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * The column <code>tue4_gear_section_configuration.gsc_ges_id</code>.
     */
    public final TableField<GearSectionConfigurationRecord, String> GSC_GES_ID = createField("gsc_ges_id",
        org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_gear_section_configuration.gsc_property_name</code>.
     */
    public final TableField<GearSectionConfigurationRecord, String> GSC_PROPERTY_NAME = createField("gsc_property_name",
        org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_gear_section_configuration.gsc_value</code>.
     */
    public final TableField<GearSectionConfigurationRecord, String> GSC_VALUE = createField("gsc_value",
        org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>tue4_gear_section_configuration</code> table reference
     */
    public Tue4GearSectionConfiguration() {
        this(DSL.name("tue4_gear_section_configuration"), null);
    }

    /**
     * Create an aliased <code>tue4_gear_section_configuration</code> table reference
     */
    public Tue4GearSectionConfiguration(String alias) {
        this(DSL.name(alias), GEAR_SECTION_CONFIGURATION);
    }

    /**
     * Create an aliased <code>tue4_gear_section_configuration</code> table reference
     */
    public Tue4GearSectionConfiguration(Name alias) {
        this(alias, GEAR_SECTION_CONFIGURATION);
    }

    private Tue4GearSectionConfiguration(Name alias, Table<GearSectionConfigurationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4GearSectionConfiguration(Name alias, Table<GearSectionConfigurationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_16676_Kue4_GSC_GES_ID_FK, Indexes.GEAR_SECTION_CONFIGURATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GearSectionConfigurationRecord> getPrimaryKey() {
        return Keys.GEAR_SECTION_CONFIGURATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GearSectionConfigurationRecord>> getKeys() {
        return Arrays.<UniqueKey<GearSectionConfigurationRecord>>asList(Keys.GEAR_SECTION_CONFIGURATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GearSectionConfigurationRecord, ?>> getReferences() {
        return Arrays
            .<ForeignKey<GearSectionConfigurationRecord, ?>>asList(Keys.GEAR_SECTION_CONFIGURATION__Tue4_GEAR_SECTION_CONFIGURATION_GSC_GES_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4GearSectionConfiguration as(String alias) {
        return new Tue4GearSectionConfiguration(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4GearSectionConfiguration as(Name alias) {
        return new Tue4GearSectionConfiguration(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4GearSectionConfiguration rename(String name) {
        return new Tue4GearSectionConfiguration(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4GearSectionConfiguration rename(Name name) {
        return new Tue4GearSectionConfiguration(name, null);
    }
}
