/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.MapcycleRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4Mapcycle extends TableImpl<MapcycleRecord> {

    private static final long serialVersionUID = 663266602;

    /**
     * The reference instance of <code>tue4_mapcycle</code>
     */
    public static final Tue4Mapcycle MAPCYCLE = new Tue4Mapcycle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapcycleRecord> getRecordType() {
        return MapcycleRecord.class;
    }

    /**
     * The column <code>tue4_mapcycle.map_id</code>.
     */
    public final TableField<MapcycleRecord, String> MAP_ID = createField("map_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_mapcycle.map_srv_id</code>.
     */
    public final TableField<MapcycleRecord, String> MAP_SRV_ID = createField("map_srv_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_mapcycle.map_alias</code>.
     */
    public final TableField<MapcycleRecord, String> MAP_ALIAS = createField("map_alias", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_mapcycle.map_mode</code>.
     */
    public final TableField<MapcycleRecord, String> MAP_MODE = createField("map_mode", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>tue4_mapcycle.map_time_of_day</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_TIME_OF_DAY = createField("map_time_of_day", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_weather</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_WEATHER = createField("map_weather", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_time_limit</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_TIME_LIMIT = createField("map_time_limit", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_max_bot_count</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_MAX_BOT_COUNT =
        createField("map_max_bot_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_max_bot_skill_level</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_MAX_BOT_SKILL_LEVEL = createField("map_max_bot_skill_level",
        org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_min_bot_skill_level</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_MIN_BOT_SKILL_LEVEL = createField("map_min_bot_skill_level",
        org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tue4_mapcycle.map_match_score_limit</code>.
     */
    public final TableField<MapcycleRecord, Integer> MAP_MATCH_SCORE_LIMIT = createField("map_match_score_limit", org.jooq.impl.SQLDataType.INTEGER,
        this, "");

    /**
     * Create a <code>tue4_mapcycle</code> table reference
     */
    public Tue4Mapcycle() {
        this(DSL.name("tue4_mapcycle"), null);
    }

    /**
     * Create an aliased <code>tue4_mapcycle</code> table reference
     */
    public Tue4Mapcycle(String alias) {
        this(DSL.name(alias), MAPCYCLE);
    }

    /**
     * Create an aliased <code>tue4_mapcycle</code> table reference
     */
    public Tue4Mapcycle(Name alias) {
        this(alias, MAPCYCLE);
    }

    private Tue4Mapcycle(Name alias, Table<MapcycleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4Mapcycle(Name alias, Table<MapcycleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MAPCYCLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MapcycleRecord> getPrimaryKey() {
        return Keys.MAPCYCLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MapcycleRecord>> getKeys() {
        return Arrays.<UniqueKey<MapcycleRecord>>asList(Keys.MAPCYCLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Mapcycle as(String alias) {
        return new Tue4Mapcycle(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Mapcycle as(Name alias) {
        return new Tue4Mapcycle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Mapcycle rename(String name) {
        return new Tue4Mapcycle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Mapcycle rename(Name name) {
        return new Tue4Mapcycle(name, null);
    }
}
