/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.LoreStarsRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4LoreStars extends TableImpl<LoreStarsRecord> {

    private static final long serialVersionUID = 1050730586;

    /**
     * The reference instance of <code>tue4_lore_stars</code>
     */
    public static final Tue4LoreStars LORE_STARS = new Tue4LoreStars();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoreStarsRecord> getRecordType() {
        return LoreStarsRecord.class;
    }

    /**
     * The column <code>tue4_lore_stars.lstar_id</code>.
     */
    public final TableField<LoreStarsRecord, String> LSTAR_ID = createField("lstar_id", org.jooq.impl.SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_stars.lstar_name</code>.
     */
    public final TableField<LoreStarsRecord, String> LSTAR_NAME = createField("lstar_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_stars.lstar_type</code>.
     */
    public final TableField<LoreStarsRecord, String> LSTAR_TYPE = createField("lstar_type", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_stars.lstar_descrip</code>.
     */
    public final TableField<LoreStarsRecord, String> LSTAR_DESCRIP = createField("lstar_descrip", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_stars.lstar_temp</code>.
     */
    public final TableField<LoreStarsRecord, Long> LSTAR_TEMP = createField("lstar_temp", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tue4_lore_stars.created_at</code>.
     */
    public final TableField<LoreStarsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tue4_lore_stars.updated_at</code>.
     */
    public final TableField<LoreStarsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tue4_lore_stars</code> table reference
     */
    public Tue4LoreStars() {
        this(DSL.name("tue4_lore_stars"), null);
    }

    /**
     * Create an aliased <code>tue4_lore_stars</code> table reference
     */
    public Tue4LoreStars(String alias) {
        this(DSL.name(alias), LORE_STARS);
    }

    /**
     * Create an aliased <code>tue4_lore_stars</code> table reference
     */
    public Tue4LoreStars(Name alias) {
        this(alias, LORE_STARS);
    }

    private Tue4LoreStars(Name alias, Table<LoreStarsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4LoreStars(Name alias, Table<LoreStarsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LORE_STARS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LoreStarsRecord> getPrimaryKey() {
        return Keys.LORE_STARS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LoreStarsRecord>> getKeys() {
        return Arrays.<UniqueKey<LoreStarsRecord>>asList(Keys.LORE_STARS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreStars as(String alias) {
        return new Tue4LoreStars(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreStars as(Name alias) {
        return new Tue4LoreStars(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreStars rename(String name) {
        return new Tue4LoreStars(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreStars rename(Name name) {
        return new Tue4LoreStars(name, null);
    }
}
