/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.InventoryInstanceRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4InventoryInstance extends TableImpl<InventoryInstanceRecord> {

    private static final long serialVersionUID = -1146398387;

    /**
     * The reference instance of <code>tue4_inventory_instance</code>
     */
    public static final Tue4InventoryInstance INVENTORY_INSTANCE = new Tue4InventoryInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryInstanceRecord> getRecordType() {
        return InventoryInstanceRecord.class;
    }

    /**
     * The column <code>tue4_inventory_instance.ini_id</code>.
     */
    public final TableField<InventoryInstanceRecord, String> INI_ID = createField("ini_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_inventory_instance.ini_ino_id</code>.
     */
    public final TableField<InventoryInstanceRecord, String> INI_INO_ID = createField("ini_ino_id", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * The column <code>tue4_inventory_instance.ini_pil_id</code>.
     */
    public final TableField<InventoryInstanceRecord, String> INI_PIL_ID = createField("ini_pil_id", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * The column <code>tue4_inventory_instance.ini_gei_id</code>.
     */
    public final TableField<InventoryInstanceRecord, String> INI_GEI_ID = createField("ini_gei_id", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * The column <code>tue4_inventory_instance.ini_inl_id</code>.
     */
    public final TableField<InventoryInstanceRecord, String> INI_INL_ID = createField("ini_inl_id", org.jooq.impl.SQLDataType.CLOB.nullable(false),
        this, "");

    /**
     * Create a <code>tue4_inventory_instance</code> table reference
     */
    public Tue4InventoryInstance() {
        this(DSL.name("tue4_inventory_instance"), null);
    }

    /**
     * Create an aliased <code>tue4_inventory_instance</code> table reference
     */
    public Tue4InventoryInstance(String alias) {
        this(DSL.name(alias), INVENTORY_INSTANCE);
    }

    /**
     * Create an aliased <code>tue4_inventory_instance</code> table reference
     */
    public Tue4InventoryInstance(Name alias) {
        this(alias, INVENTORY_INSTANCE);
    }

    private Tue4InventoryInstance(Name alias, Table<InventoryInstanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4InventoryInstance(Name alias, Table<InventoryInstanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INVENTORY_INSTANCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InventoryInstanceRecord> getPrimaryKey() {
        return Keys.INVENTORY_INSTANCE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InventoryInstanceRecord>> getKeys() {
        return Arrays.<UniqueKey<InventoryInstanceRecord>>asList(Keys.INVENTORY_INSTANCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InventoryInstanceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InventoryInstanceRecord, ?>>asList(Keys.INVENTORY_INSTANCE__Tue4_INVENTORY_INSTANCE_INI_INO_ID_FKEY,
            Keys.INVENTORY_INSTANCE__Tue4_INVENTORY_INSTANCE_INI_PIL_ID_FKEY, Keys.INVENTORY_INSTANCE__Tue4_INVENTORY_INSTANCE_INI_GEI_ID_FKEY,
            Keys.INVENTORY_INSTANCE__Tue4_INVENTORY_INSTANCE_INI_INL_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4InventoryInstance as(String alias) {
        return new Tue4InventoryInstance(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4InventoryInstance as(Name alias) {
        return new Tue4InventoryInstance(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4InventoryInstance rename(String name) {
        return new Tue4InventoryInstance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4InventoryInstance rename(Name name) {
        return new Tue4InventoryInstance(name, null);
    }
}
