/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.BmAccountsRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4BmAccounts extends TableImpl<BmAccountsRecord> {

    private static final long serialVersionUID = -1048023248;

    /**
     * The reference instance of <code>tue4_bm_accounts</code>
     */
    public static final Tue4BmAccounts BM_ACCOUNTS = new Tue4BmAccounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BmAccountsRecord> getRecordType() {
        return BmAccountsRecord.class;
    }

    /**
     * The column <code>tue4_bm_accounts.bm_accounts_id</code>.
     */
    public final TableField<BmAccountsRecord, String> BM_ACCOUNTS_ID = createField("bm_accounts_id",
        org.jooq.impl.SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>tue4_bm_accounts.pil_id</code>.
     */
    public final TableField<BmAccountsRecord, String> PIL_ID = createField("pil_id", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>tue4_bm_accounts.bm_corp_id</code>.
     */
    public final TableField<BmAccountsRecord, String> BM_CORP_ID = createField("bm_corp_id", org.jooq.impl.SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>tue4_bm_accounts.bm_accstatus</code>.
     */
    public final TableField<BmAccountsRecord, String> BM_ACCSTATUS = createField("bm_accstatus",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_bm_accounts.bm_accounttype</code>.
     */
    public final TableField<BmAccountsRecord, String> BM_ACCOUNTTYPE = createField("bm_accounttype",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_bm_accounts.bm_accountbalance</code>.
     */
    public final TableField<BmAccountsRecord, Double> BM_ACCOUNTBALANCE = createField("bm_accountbalance",
        org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>tue4_bm_accounts.created_at</code>.
     */
    public final TableField<BmAccountsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tue4_bm_accounts.updated_at</code>.
     */
    public final TableField<BmAccountsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tue4_bm_accounts</code> table reference
     */
    public Tue4BmAccounts() {
        this(DSL.name("tue4_bm_accounts"), null);
    }

    /**
     * Create an aliased <code>tue4_bm_accounts</code> table reference
     */
    public Tue4BmAccounts(String alias) {
        this(DSL.name(alias), BM_ACCOUNTS);
    }

    /**
     * Create an aliased <code>tue4_bm_accounts</code> table reference
     */
    public Tue4BmAccounts(Name alias) {
        this(alias, BM_ACCOUNTS);
    }

    private Tue4BmAccounts(Name alias, Table<BmAccountsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4BmAccounts(Name alias, Table<BmAccountsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BM_ACCOUNTS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BmAccountsRecord> getPrimaryKey() {
        return Keys.BM_ACCOUNTS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BmAccountsRecord>> getKeys() {
        return Arrays.<UniqueKey<BmAccountsRecord>>asList(Keys.BM_ACCOUNTS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4BmAccounts as(String alias) {
        return new Tue4BmAccounts(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4BmAccounts as(Name alias) {
        return new Tue4BmAccounts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4BmAccounts rename(String name) {
        return new Tue4BmAccounts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4BmAccounts rename(Name name) {
        return new Tue4BmAccounts(name, null);
    }
}
