/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.MapRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4Map extends TableImpl<MapRecord> {

    private static final long serialVersionUID = 652572191;

    /**
     * The reference instance of <code>tue4_map</code>
     */
    public static final Tue4Map MAP = new Tue4Map();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapRecord> getRecordType() {
        return MapRecord.class;
    }

    /**
     * The column <code>tue4_map.map_id</code>.
     */
    public final TableField<MapRecord, String> MAP_ID = createField("map_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tue4_map.map_asset_name</code>.
     */
    public final TableField<MapRecord, String> MAP_ASSET_NAME = createField("map_asset_name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>tue4_map</code> table reference
     */
    public Tue4Map() {
        this(DSL.name("tue4_map"), null);
    }

    /**
     * Create an aliased <code>tue4_map</code> table reference
     */
    public Tue4Map(String alias) {
        this(DSL.name(alias), MAP);
    }

    /**
     * Create an aliased <code>tue4_map</code> table reference
     */
    public Tue4Map(Name alias) {
        this(alias, MAP);
    }

    private Tue4Map(Name alias, Table<MapRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4Map(Name alias, Table<MapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MAP_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MapRecord> getPrimaryKey() {
        return Keys.MAP_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MapRecord>> getKeys() {
        return Arrays.<UniqueKey<MapRecord>>asList(Keys.MAP_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Map as(String alias) {
        return new Tue4Map(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4Map as(Name alias) {
        return new Tue4Map(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Map rename(String name) {
        return new Tue4Map(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4Map rename(Name name) {
        return new Tue4Map(name, null);
    }
}
