/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.DefaultSchema;
import com.tokenplay.ue4.model.db.Indexes;
import com.tokenplay.ue4.model.db.Keys;
import com.tokenplay.ue4.model.db.tables.records.LoreCircuitsRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Tue4LoreCircuits extends TableImpl<LoreCircuitsRecord> {

    private static final long serialVersionUID = -2080979597;

    /**
     * The reference instance of <code>tue4_lore_circuits</code>
     */
    public static final Tue4LoreCircuits LORE_CIRCUITS = new Tue4LoreCircuits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoreCircuitsRecord> getRecordType() {
        return LoreCircuitsRecord.class;
    }

    /**
     * The column <code>tue4_lore_circuits.lcir_id</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_ID =
        createField("lcir_id", org.jooq.impl.SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_circuits.lcir_lpla_id</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_LPLA_ID = createField("lcir_lpla_id",
        org.jooq.impl.SQLDataType.CHAR(32).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_circuits.lcir_hemisphere</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_HEMISPHERE = createField("lcir_hemisphere", org.jooq.impl.SQLDataType.VARCHAR(255)
        .nullable(false), this, "");

    /**
     * The column <code>tue4_lore_circuits.lcir_class</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_CLASS = createField("lcir_class",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_circuits.lcir_league</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_LEAGUE = createField("lcir_league",
        org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tue4_lore_circuits.lcir_name</code>.
     */
    public final TableField<LoreCircuitsRecord, String> LCIR_NAME = createField("lcir_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false),
        this, "");

    /**
     * The column <code>tue4_lore_circuits.created_at</code>.
     */
    public final TableField<LoreCircuitsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tue4_lore_circuits.updated_at</code>.
     */
    public final TableField<LoreCircuitsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false)
        .defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tue4_lore_circuits</code> table reference
     */
    public Tue4LoreCircuits() {
        this(DSL.name("tue4_lore_circuits"), null);
    }

    /**
     * Create an aliased <code>tue4_lore_circuits</code> table reference
     */
    public Tue4LoreCircuits(String alias) {
        this(DSL.name(alias), LORE_CIRCUITS);
    }

    /**
     * Create an aliased <code>tue4_lore_circuits</code> table reference
     */
    public Tue4LoreCircuits(Name alias) {
        this(alias, LORE_CIRCUITS);
    }

    private Tue4LoreCircuits(Name alias, Table<LoreCircuitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tue4LoreCircuits(Name alias, Table<LoreCircuitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LORE_CIRCUITS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LoreCircuitsRecord> getPrimaryKey() {
        return Keys.LORE_CIRCUITS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LoreCircuitsRecord>> getKeys() {
        return Arrays.<UniqueKey<LoreCircuitsRecord>>asList(Keys.LORE_CIRCUITS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreCircuits as(String alias) {
        return new Tue4LoreCircuits(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tue4LoreCircuits as(Name alias) {
        return new Tue4LoreCircuits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreCircuits rename(String name) {
        return new Tue4LoreCircuits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tue4LoreCircuits rename(Name name) {
        return new Tue4LoreCircuits(name, null);
    }
}
