/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class BmOrder implements Serializable {

    private static final long serialVersionUID = -792559492;

    private String bmOrderId;
    private String id;
    private String corpId;
    private String bmTransactionId;
    private String bmEquipmentId;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public BmOrder() {
    }

    public BmOrder(BmOrder value) {
        this.bmOrderId = value.bmOrderId;
        this.id = value.id;
        this.corpId = value.corpId;
        this.bmTransactionId = value.bmTransactionId;
        this.bmEquipmentId = value.bmEquipmentId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public BmOrder(String bmOrderId, String id, String corpId, String bmTransactionId, String bmEquipmentId, Timestamp createdAt, Timestamp updatedAt) {
        this.bmOrderId = bmOrderId;
        this.id = id;
        this.corpId = corpId;
        this.bmTransactionId = bmTransactionId;
        this.bmEquipmentId = bmEquipmentId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @NotNull
    @Size(max = 32)
    public String getBmOrderId() {
        return this.bmOrderId;
    }

    public void setBmOrderId(String bmOrderId) {
        this.bmOrderId = bmOrderId;
    }

    @Size(max = 32)
    public String getPilId() {
        return this.id;
    }

    public void setPilId(String id) {
        this.id = id;
    }

    @Size(max = 32)
    public String getCorpId() {
        return this.corpId;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    @NotNull
    @Size(max = 32)
    public String getBmTransactionId() {
        return this.bmTransactionId;
    }

    public void setBmTransactionId(String bmTransactionId) {
        this.bmTransactionId = bmTransactionId;
    }

    @NotNull
    @Size(max = 32)
    public String getBmEquipmentId() {
        return this.bmEquipmentId;
    }

    public void setBmEquipmentId(String bmEquipmentId) {
        this.bmEquipmentId = bmEquipmentId;
    }

    @NotNull
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @NotNull
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BmOrder (");

        sb.append(bmOrderId);
        sb.append(", ").append(id);
        sb.append(", ").append(corpId);
        sb.append(", ").append(bmTransactionId);
        sb.append(", ").append(bmEquipmentId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
