/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class ConfigItem implements Serializable {

    private static final long serialVersionUID = 455896717;

    private String id;
    private String value;
    private String pilId;

    public ConfigItem() {
    }

    public ConfigItem(ConfigItem value) {
        this.id = value.id;
        this.value = value.value;
        this.pilId = value.pilId;
    }

    public ConfigItem(String id, String value, String pilId) {
        this.id = id;
        this.value = value;
        this.pilId = pilId;
    }

    @NotNull
    public String getCfiId() {
        return this.id;
    }

    public void setCfiId(String id) {
        this.id = id;
    }

    @NotNull
    public String getCfiValue() {
        return this.value;
    }

    public void setCfiValue(String value) {
        this.value = value;
    }

    @NotNull
    public String getCfiPilId() {
        return this.pilId;
    }

    public void setCfiPilId(String pilId) {
        this.pilId = pilId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfigItem (");

        sb.append(id);
        sb.append(", ").append(value);
        sb.append(", ").append(pilId);

        sb.append(")");
        return sb.toString();
    }
}
