/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class GameMode implements Serializable {

    private static final long serialVersionUID = 1360597215;

    private String id;
    private String assetName;

    public GameMode() {
    }

    public GameMode(GameMode value) {
        this.id = value.id;
        this.assetName = value.assetName;
    }

    public GameMode(String id, String assetName) {
        this.id = id;
        this.assetName = assetName;
    }

    @NotNull
    public String getGamId() {
        return this.id;
    }

    public void setGamId(String id) {
        this.id = id;
    }

    public String getGamAssetName() {
        return this.assetName;
    }

    public void setGamAssetName(String assetName) {
        this.assetName = assetName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GameMode (");

        sb.append(id);
        sb.append(", ").append(assetName);

        sb.append(")");
        return sb.toString();
    }
}
