/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class InventoryInstance implements Serializable {

    private static final long serialVersionUID = 1619214051;

    private String id;
    private String inoId;
    private String pilId;
    private String geiId;
    private String inlId;

    public InventoryInstance() {
    }

    public InventoryInstance(InventoryInstance value) {
        this.id = value.id;
        this.inoId = value.inoId;
        this.pilId = value.pilId;
        this.geiId = value.geiId;
        this.inlId = value.inlId;
    }

    public InventoryInstance(String id, String inoId, String pilId, String geiId, String inlId) {
        this.id = id;
        this.inoId = inoId;
        this.pilId = pilId;
        this.geiId = geiId;
        this.inlId = inlId;
    }

    @NotNull
    public String getIniId() {
        return this.id;
    }

    public void setIniId(String id) {
        this.id = id;
    }

    @NotNull
    public String getIniInoId() {
        return this.inoId;
    }

    public void setIniInoId(String inoId) {
        this.inoId = inoId;
    }

    @NotNull
    public String getIniPilId() {
        return this.pilId;
    }

    public void setIniPilId(String pilId) {
        this.pilId = pilId;
    }

    @NotNull
    public String getIniGeiId() {
        return this.geiId;
    }

    public void setIniGeiId(String geiId) {
        this.geiId = geiId;
    }

    @NotNull
    public String getIniInlId() {
        return this.inlId;
    }

    public void setIniInlId(String inlId) {
        this.inlId = inlId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InventoryInstance (");

        sb.append(id);
        sb.append(", ").append(inoId);
        sb.append(", ").append(pilId);
        sb.append(", ").append(geiId);
        sb.append(", ").append(inlId);

        sb.append(")");
        return sb.toString();
    }
}
