/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class LoreCircuits implements Serializable {

    private static final long serialVersionUID = 1795142273;

    private String lcirId;
    private String lcirLplaId;
    private String lcirHemisphere;
    private String lcirClass;
    private String lcirLeague;
    private String lcirName;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public LoreCircuits() {
    }

    public LoreCircuits(LoreCircuits value) {
        this.lcirId = value.lcirId;
        this.lcirLplaId = value.lcirLplaId;
        this.lcirHemisphere = value.lcirHemisphere;
        this.lcirClass = value.lcirClass;
        this.lcirLeague = value.lcirLeague;
        this.lcirName = value.lcirName;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public LoreCircuits(String lcirId, String lcirLplaId, String lcirHemisphere, String lcirClass, String lcirLeague, String lcirName,
        Timestamp createdAt, Timestamp updatedAt) {
        this.lcirId = lcirId;
        this.lcirLplaId = lcirLplaId;
        this.lcirHemisphere = lcirHemisphere;
        this.lcirClass = lcirClass;
        this.lcirLeague = lcirLeague;
        this.lcirName = lcirName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @NotNull
    @Size(max = 32)
    public String getLcirId() {
        return this.lcirId;
    }

    public void setLcirId(String lcirId) {
        this.lcirId = lcirId;
    }

    @NotNull
    @Size(max = 32)
    public String getLcirLplaId() {
        return this.lcirLplaId;
    }

    public void setLcirLplaId(String lcirLplaId) {
        this.lcirLplaId = lcirLplaId;
    }

    @NotNull
    @Size(max = 255)
    public String getLcirHemisphere() {
        return this.lcirHemisphere;
    }

    public void setLcirHemisphere(String lcirHemisphere) {
        this.lcirHemisphere = lcirHemisphere;
    }

    @NotNull
    @Size(max = 255)
    public String getLcirClass() {
        return this.lcirClass;
    }

    public void setLcirClass(String lcirClass) {
        this.lcirClass = lcirClass;
    }

    @NotNull
    @Size(max = 255)
    public String getLcirLeague() {
        return this.lcirLeague;
    }

    public void setLcirLeague(String lcirLeague) {
        this.lcirLeague = lcirLeague;
    }

    @NotNull
    @Size(max = 255)
    public String getLcirName() {
        return this.lcirName;
    }

    public void setLcirName(String lcirName) {
        this.lcirName = lcirName;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoreCircuits (");

        sb.append(lcirId);
        sb.append(", ").append(lcirLplaId);
        sb.append(", ").append(lcirHemisphere);
        sb.append(", ").append(lcirClass);
        sb.append(", ").append(lcirLeague);
        sb.append(", ").append(lcirName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
