/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class Orders implements Serializable {

    private static final long serialVersionUID = -922593830;

    private Long id;
    private Long userId;
    private Long billingId;
    private Long shippingId;
    private BigDecimal total;
    private String status;
    private String processor;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private OffsetDateTime equipmentProcessedAt;

    public Orders() {
    }

    public Orders(Orders value) {
        this.id = value.id;
        this.userId = value.userId;
        this.billingId = value.billingId;
        this.shippingId = value.shippingId;
        this.total = value.total;
        this.status = value.status;
        this.processor = value.processor;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.equipmentProcessedAt = value.equipmentProcessedAt;
    }

    public Orders(Long id, Long userId, Long billingId, Long shippingId, BigDecimal total, String status, String processor, OffsetDateTime createdAt,
        OffsetDateTime updatedAt, OffsetDateTime equipmentProcessedAt) {
        this.id = id;
        this.userId = userId;
        this.billingId = billingId;
        this.shippingId = shippingId;
        this.total = total;
        this.status = status;
        this.processor = processor;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.equipmentProcessedAt = equipmentProcessedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getBillingId() {
        return this.billingId;
    }

    public void setBillingId(Long billingId) {
        this.billingId = billingId;
    }

    public Long getShippingId() {
        return this.shippingId;
    }

    public void setShippingId(Long shippingId) {
        this.shippingId = shippingId;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getProcessor() {
        return this.processor;
    }

    public void setProcessor(String processor) {
        this.processor = processor;
    }

    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public OffsetDateTime getEquipmentProcessedAt() {
        return this.equipmentProcessedAt;
    }

    public void setEquipmentProcessedAt(OffsetDateTime equipmentProcessedAt) {
        this.equipmentProcessedAt = equipmentProcessedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(billingId);
        sb.append(", ").append(shippingId);
        sb.append(", ").append(total);
        sb.append(", ").append(status);
        sb.append(", ").append(processor);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(equipmentProcessedAt);

        sb.append(")");
        return sb.toString();
    }
}
