/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4Allegiance;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class AllegianceRecord extends UpdatableRecordImpl<AllegianceRecord> implements
    Record6<String, String, OffsetDateTime, OffsetDateTime, Long, String> {

    private static final long serialVersionUID = -2020701397;

    /**
     * Setter for <code>tue4_allegiance.ali_pil_id</code>.
     */
    public void setAliPilId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_pil_id</code>.
     */
    @NotNull
    public String getAliPilId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_allegiance.ali_sta_id</code>.
     */
    public void setAliStaId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_sta_id</code>.
     */
    @NotNull
    public String getAliStaId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_allegiance.ali_date_init</code>.
     */
    public void setAliDateInit(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_date_init</code>.
     */
    @NotNull
    public OffsetDateTime getAliDateInit() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>tue4_allegiance.ali_date_end</code>.
     */
    public void setAliDateEnd(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_date_end</code>.
     */
    @NotNull
    public OffsetDateTime getAliDateEnd() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>tue4_allegiance.ali_rank_number</code>.
     */
    public void setAliRankNumber(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_rank_number</code>.
     */
    @NotNull
    public Long getAliRankNumber() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>tue4_allegiance.ali_rank</code>.
     */
    public void setAliRank(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_allegiance.ali_rank</code>.
     */
    @NotNull
    public String getAliRank() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, OffsetDateTime, OffsetDateTime, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, OffsetDateTime, OffsetDateTime, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4Allegiance.ALLEGIANCE.ALI_PIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4Allegiance.ALLEGIANCE.ALI_STA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return Tue4Allegiance.ALLEGIANCE.ALI_DATE_INIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field4() {
        return Tue4Allegiance.ALLEGIANCE.ALI_DATE_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Tue4Allegiance.ALLEGIANCE.ALI_RANK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tue4Allegiance.ALLEGIANCE.ALI_RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAliPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAliStaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getAliDateInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component4() {
        return getAliDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAliRankNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAliRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAliPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAliStaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getAliDateInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value4() {
        return getAliDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAliRankNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAliRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value1(String value) {
        setAliPilId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value2(String value) {
        setAliStaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value3(OffsetDateTime value) {
        setAliDateInit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value4(OffsetDateTime value) {
        setAliDateEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value5(Long value) {
        setAliRankNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord value6(String value) {
        setAliRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllegianceRecord values(String value1, String value2, OffsetDateTime value3, OffsetDateTime value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllegianceRecord
     */
    public AllegianceRecord() {
        super(Tue4Allegiance.ALLEGIANCE);
    }

    /**
     * Create a detached, initialised AllegianceRecord
     */
    public AllegianceRecord(String pilId, String staId, OffsetDateTime dateInit, OffsetDateTime dateEnd, Long rankNumber, String rank) {
        super(Tue4Allegiance.ALLEGIANCE);

        set(0, pilId);
        set(1, staId);
        set(2, dateInit);
        set(3, dateEnd);
        set(4, rankNumber);
        set(5, rank);
    }
}
