/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4BmAssets;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class BmAssetsRecord extends UpdatableRecordImpl<BmAssetsRecord> implements
    Record10<String, String, String, String, String, String, Timestamp, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = -1504275266;

    /**
     * Setter for <code>tue4_bm_assets.bm_asset_id</code>.
     */
    public void setBmAssetId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_asset_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getBmAssetId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_pil_id</code>.
     */
    public void setBmPilId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_pil_id</code>.
     */
    @Size(max = 32)
    public String getBmPilId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_default_id</code>.
     */
    public void setBmDefaultId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_default_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getBmDefaultId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_parent_id</code>.
     */
    public void setBmParentId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_parent_id</code>.
     */
    @Size(max = 32)
    public String getBmParentId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_asset_matchid</code>.
     */
    public void setBmAssetMatchid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_asset_matchid</code>.
     */
    @Size(max = 255)
    public String getBmAssetMatchid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_asset_pjson</code>.
     */
    public void setBmAssetPjson(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_asset_pjson</code>.
     */
    @Size(max = 255)
    public String getBmAssetPjson() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tue4_bm_assets.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>tue4_bm_assets.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_ord_id</code>.
     */
    public void setBmOrdId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_ord_id</code>.
     */
    public Integer getBmOrdId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>tue4_bm_assets.bm_ple_id</code>.
     */
    public void setBmPleId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>tue4_bm_assets.bm_ple_id</code>.
     */
    public Integer getBmPleId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Timestamp, Timestamp, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Timestamp, Timestamp, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4BmAssets.BM_ASSETS.BM_ASSET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4BmAssets.BM_ASSETS.BM_PIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4BmAssets.BM_ASSETS.BM_DEFAULT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tue4BmAssets.BM_ASSETS.BM_PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tue4BmAssets.BM_ASSETS.BM_ASSET_MATCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tue4BmAssets.BM_ASSETS.BM_ASSET_PJSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Tue4BmAssets.BM_ASSETS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Tue4BmAssets.BM_ASSETS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Tue4BmAssets.BM_ASSETS.BM_ORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Tue4BmAssets.BM_ASSETS.BM_PLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getBmAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBmPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBmDefaultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBmParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBmAssetMatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBmAssetPjson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getBmOrdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getBmPleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBmAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBmPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBmDefaultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBmParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBmAssetMatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBmAssetPjson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getBmOrdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getBmPleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value1(String value) {
        setBmAssetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value2(String value) {
        setBmPilId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value3(String value) {
        setBmDefaultId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value4(String value) {
        setBmParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value5(String value) {
        setBmAssetMatchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value6(String value) {
        setBmAssetPjson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value9(Integer value) {
        setBmOrdId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord value10(Integer value) {
        setBmPleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmAssetsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7,
        Timestamp value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BmAssetsRecord
     */
    public BmAssetsRecord() {
        super(Tue4BmAssets.BM_ASSETS);
    }

    /**
     * Create a detached, initialised BmAssetsRecord
     */
    public BmAssetsRecord(String bmAssetId, String bmPilId, String bmDefaultId, String bmParentId, String bmAssetMatchid, String bmAssetPjson,
        Timestamp createdAt, Timestamp updatedAt, Integer bmOrdId, Integer bmPleId) {
        super(Tue4BmAssets.BM_ASSETS);

        set(0, bmAssetId);
        set(1, bmPilId);
        set(2, bmDefaultId);
        set(3, bmParentId);
        set(4, bmAssetMatchid);
        set(5, bmAssetPjson);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, bmOrdId);
        set(9, bmPleId);
    }
}
