/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4BmTransactions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class BmTransactionsRecord extends UpdatableRecordImpl<BmTransactionsRecord> implements
    Record8<String, String, String, Double, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -1462735756;

    /**
     * Setter for <code>tue4_bm_transactions.bm_transactions_id</code>.
     */
    public void setBmTransactionsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_transactions_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getBmTransactionsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_bm_transactions.bm_transfer_id</code>.
     */
    public void setBmTransferId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_transfer_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getBmTransferId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_bm_transactions.bm_accounts_id</code>.
     */
    public void setBmAccountsId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_accounts_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getBmAccountsId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_bm_transactions.bm_amount</code>.
     */
    public void setBmAmount(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_amount</code>.
     */
    @NotNull
    public Double getBmAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>tue4_bm_transactions.bm_paymentstatus</code>.
     */
    public void setBmPaymentstatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_paymentstatus</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getBmPaymentstatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tue4_bm_transactions.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>tue4_bm_transactions.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>tue4_bm_transactions.bm_asset_id</code>.
     */
    public void setBmAssetId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_bm_transactions.bm_asset_id</code>.
     */
    @Size(max = 32)
    public String getBmAssetId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, Double, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, Double, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_TRANSACTIONS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_TRANSFER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_ACCOUNTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_PAYMENTSTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Tue4BmTransactions.BM_TRANSACTIONS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Tue4BmTransactions.BM_TRANSACTIONS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Tue4BmTransactions.BM_TRANSACTIONS.BM_ASSET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getBmTransactionsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBmTransferId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBmAccountsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getBmAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBmPaymentstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBmAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBmTransactionsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBmTransferId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBmAccountsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getBmAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBmPaymentstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBmAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value1(String value) {
        setBmTransactionsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value2(String value) {
        setBmTransferId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value3(String value) {
        setBmAccountsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value4(Double value) {
        setBmAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value5(String value) {
        setBmPaymentstatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord value8(String value) {
        setBmAssetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmTransactionsRecord values(String value1, String value2, String value3, Double value4, String value5, Timestamp value6, Timestamp value7,
        String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BmTransactionsRecord
     */
    public BmTransactionsRecord() {
        super(Tue4BmTransactions.BM_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised BmTransactionsRecord
     */
    public BmTransactionsRecord(String bmTransactionsId, String bmTransferId, String bmAccountsId, Double bmAmount, String bmPaymentstatus,
        Timestamp createdAt, Timestamp updatedAt, String bmAssetId) {
        super(Tue4BmTransactions.BM_TRANSACTIONS);

        set(0, bmTransactionsId);
        set(1, bmTransferId);
        set(2, bmAccountsId);
        set(3, bmAmount);
        set(4, bmPaymentstatus);
        set(5, createdAt);
        set(6, updatedAt);
        set(7, bmAssetId);
    }
}
