/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4Championship;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class ChampionshipRecord extends UpdatableRecordImpl<ChampionshipRecord> implements Record5<String, String, String, Date, Date> {

    private static final long serialVersionUID = -799200620;

    /**
     * Setter for <code>tue4_championship.cha_id</code>.
     */
    public void setChaId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_championship.cha_id</code>.
     */
    @NotNull
    public String getChaId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_championship.cha_name</code>.
     */
    public void setChaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_championship.cha_name</code>.
     */
    @NotNull
    public String getChaName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_championship.cha_description</code>.
     */
    public void setChaDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_championship.cha_description</code>.
     */
    @NotNull
    public String getChaDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_championship.cha_date_init</code>.
     */
    public void setChaDateInit(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_championship.cha_date_init</code>.
     */
    @NotNull
    public Date getChaDateInit() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>tue4_championship.cha_date_end</code>.
     */
    public void setChaDateEnd(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_championship.cha_date_end</code>.
     */
    @NotNull
    public Date getChaDateEnd() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Date, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Date, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4Championship.CHAMPIONSHIP.CHA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4Championship.CHAMPIONSHIP.CHA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4Championship.CHAMPIONSHIP.CHA_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Tue4Championship.CHAMPIONSHIP.CHA_DATE_INIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Tue4Championship.CHAMPIONSHIP.CHA_DATE_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getChaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getChaDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getChaDateInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getChaDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getChaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getChaDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getChaDateInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getChaDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord value1(String value) {
        setChaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord value2(String value) {
        setChaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord value3(String value) {
        setChaDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord value4(Date value) {
        setChaDateInit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord value5(Date value) {
        setChaDateEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChampionshipRecord values(String value1, String value2, String value3, Date value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChampionshipRecord
     */
    public ChampionshipRecord() {
        super(Tue4Championship.CHAMPIONSHIP);
    }

    /**
     * Create a detached, initialised ChampionshipRecord
     */
    public ChampionshipRecord(String id, String name, String description, Date dateInit, Date dateEnd) {
        super(Tue4Championship.CHAMPIONSHIP);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, dateInit);
        set(4, dateEnd);
    }
}
