/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4ConfigItem;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class ConfigItemRecord extends UpdatableRecordImpl<ConfigItemRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -421821504;

    /**
     * Setter for <code>tue4_config_item.cfi_id</code>.
     */
    public void setCfiId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_config_item.cfi_id</code>.
     */
    @NotNull
    public String getCfiId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_config_item.cfi_value</code>.
     */
    public void setCfiValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_config_item.cfi_value</code>.
     */
    @NotNull
    public String getCfiValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_config_item.cfi_pil_id</code>.
     */
    public void setCfiPilId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_config_item.cfi_pil_id</code>.
     */
    @NotNull
    public String getCfiPilId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4ConfigItem.CONFIG_ITEM.CFI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4ConfigItem.CONFIG_ITEM.CFI_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4ConfigItem.CONFIG_ITEM.CFI_PIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getCfiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCfiValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCfiPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCfiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCfiValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCfiPilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigItemRecord value1(String value) {
        setCfiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigItemRecord value2(String value) {
        setCfiValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigItemRecord value3(String value) {
        setCfiPilId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigItemRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigItemRecord
     */
    public ConfigItemRecord() {
        super(Tue4ConfigItem.CONFIG_ITEM);
    }

    /**
     * Create a detached, initialised ConfigItemRecord
     */
    public ConfigItemRecord(String id, String value, String pilId) {
        super(Tue4ConfigItem.CONFIG_ITEM);

        set(0, id);
        set(1, value);
        set(2, pilId);
    }
}
