/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4EquipmentAwarded;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class EquipmentAwardedRecord extends UpdatableRecordImpl<EquipmentAwardedRecord> implements Record4<Long, String, BigDecimal, OffsetDateTime> {

    private static final long serialVersionUID = -608284610;

    /**
     * Setter for <code>tue4_equipment_awarded.eqa_product_id</code>.
     */
    public void setEqaProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_equipment_awarded.eqa_product_id</code>.
     */
    @NotNull
    public Long getEqaProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tue4_equipment_awarded.eqa_awarded_leq_id</code>.
     */
    public void setEqaAwardedLeqId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_equipment_awarded.eqa_awarded_leq_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getEqaAwardedLeqId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_equipment_awarded.eqa_quantity</code>.
     */
    public void setEqaQuantity(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_equipment_awarded.eqa_quantity</code>.
     */
    public BigDecimal getEqaQuantity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>tue4_equipment_awarded.eqa_created_at</code>.
     */
    public void setEqaCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_equipment_awarded.eqa_created_at</code>.
     */
    public OffsetDateTime getEqaCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, BigDecimal, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, BigDecimal, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tue4EquipmentAwarded.EQUIPMENT_AWARDED.EQA_PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4EquipmentAwarded.EQUIPMENT_AWARDED.EQA_AWARDED_LEQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Tue4EquipmentAwarded.EQUIPMENT_AWARDED.EQA_QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field4() {
        return Tue4EquipmentAwarded.EQUIPMENT_AWARDED.EQA_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getEqaProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEqaAwardedLeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getEqaQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component4() {
        return getEqaCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getEqaProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEqaAwardedLeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getEqaQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value4() {
        return getEqaCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EquipmentAwardedRecord value1(Long value) {
        setEqaProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EquipmentAwardedRecord value2(String value) {
        setEqaAwardedLeqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EquipmentAwardedRecord value3(BigDecimal value) {
        setEqaQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EquipmentAwardedRecord value4(OffsetDateTime value) {
        setEqaCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EquipmentAwardedRecord values(Long value1, String value2, BigDecimal value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EquipmentAwardedRecord
     */
    public EquipmentAwardedRecord() {
        super(Tue4EquipmentAwarded.EQUIPMENT_AWARDED);
    }

    /**
     * Create a detached, initialised EquipmentAwardedRecord
     */
    public EquipmentAwardedRecord(Long productId, String awardedLeqId, BigDecimal quantity, OffsetDateTime createdAt) {
        super(Tue4EquipmentAwarded.EQUIPMENT_AWARDED);

        set(0, productId);
        set(1, awardedLeqId);
        set(2, quantity);
        set(3, createdAt);
    }
}
