/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4GameMode;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class GameModeRecord extends UpdatableRecordImpl<GameModeRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1112668492;

    /**
     * Setter for <code>tue4_game_mode.gam_id</code>.
     */
    public void setGamId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_game_mode.gam_id</code>.
     */
    @NotNull
    public String getGamId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_game_mode.gam_asset_name</code>.
     */
    public void setGamAssetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_game_mode.gam_asset_name</code>.
     */
    public String getGamAssetName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4GameMode.GAME_MODE.GAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4GameMode.GAME_MODE.GAM_ASSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGamAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGamAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameModeRecord value1(String value) {
        setGamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameModeRecord value2(String value) {
        setGamAssetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameModeRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameModeRecord
     */
    public GameModeRecord() {
        super(Tue4GameMode.GAME_MODE);
    }

    /**
     * Create a detached, initialised GameModeRecord
     */
    public GameModeRecord(String id, String assetName) {
        super(Tue4GameMode.GAME_MODE);

        set(0, id);
        set(1, assetName);
    }
}
