/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4GearModel;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class GearModelRecord extends UpdatableRecordImpl<GearModelRecord> {

    private static final long serialVersionUID = -1857340915;

    /**
     * Setter for <code>tue4_gear_model.gem_id</code>.
     */
    public void setGemId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_id</code>.
     */
    @NotNull
    public String getGemId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_name</code>.
     */
    public void setGemName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_name</code>.
     */
    @NotNull
    public String getGemName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_selectable</code>.
     */
    public void setGemSelectable(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_selectable</code>.
     */
    public Boolean getGemSelectable() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_engine</code>.
     */
    public void setGemGesEngine(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_engine</code>.
     */
    public String getGemGesEngine() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_fuel_tank</code>.
     */
    public void setGemGesFuelTank(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_fuel_tank</code>.
     */
    public String getGemGesFuelTank() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_pylon_right</code>.
     */
    public void setGemGesPylonRight(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_pylon_right</code>.
     */
    public String getGemGesPylonRight() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_pylon_left</code>.
     */
    public void setGemGesPylonLeft(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_pylon_left</code>.
     */
    public String getGemGesPylonLeft() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_foot_right</code>.
     */
    public void setGemGesFootRight(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_foot_right</code>.
     */
    public String getGemGesFootRight() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_foot_left</code>.
     */
    public void setGemGesFootLeft(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_foot_left</code>.
     */
    public String getGemGesFootLeft() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_leg_right</code>.
     */
    public void setGemGesUpperLegRight(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_leg_right</code>.
     */
    public String getGemGesUpperLegRight() {
        return (String) get(9);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_leg_left</code>.
     */
    public void setGemGesUpperLegLeft(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_leg_left</code>.
     */
    public String getGemGesUpperLegLeft() {
        return (String) get(10);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_lower_leg_right</code>.
     */
    public void setGemGesLowerLegRight(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_lower_leg_right</code>.
     */
    public String getGemGesLowerLegRight() {
        return (String) get(11);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_lower_leg_left</code>.
     */
    public void setGemGesLowerLegLeft(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_lower_leg_left</code>.
     */
    public String getGemGesLowerLegLeft() {
        return (String) get(12);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_hand_right</code>.
     */
    public void setGemGesHandRight(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_hand_right</code>.
     */
    public String getGemGesHandRight() {
        return (String) get(13);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_hand_left</code>.
     */
    public void setGemGesHandLeft(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_hand_left</code>.
     */
    public String getGemGesHandLeft() {
        return (String) get(14);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_lower_arm_right</code>.
     */
    public void setGemGesLowerArmRight(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_lower_arm_right</code>.
     */
    public String getGemGesLowerArmRight() {
        return (String) get(15);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_lower_arm_left</code>.
     */
    public void setGemGesLowerArmLeft(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_lower_arm_left</code>.
     */
    public String getGemGesLowerArmLeft() {
        return (String) get(16);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_arm_right</code>.
     */
    public void setGemGesUpperArmRight(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_arm_right</code>.
     */
    public String getGemGesUpperArmRight() {
        return (String) get(17);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_arm_left</code>.
     */
    public void setGemGesUpperArmLeft(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_arm_left</code>.
     */
    public String getGemGesUpperArmLeft() {
        return (String) get(18);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_shoulder_right</code>.
     */
    public void setGemGesShoulderRight(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_shoulder_right</code>.
     */
    public String getGemGesShoulderRight() {
        return (String) get(19);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_shoulder_left</code>.
     */
    public void setGemGesShoulderLeft(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_shoulder_left</code>.
     */
    public String getGemGesShoulderLeft() {
        return (String) get(20);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_head</code>.
     */
    public void setGemGesHead(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_head</code>.
     */
    public String getGemGesHead() {
        return (String) get(21);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_hip</code>.
     */
    public void setGemGesHip(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_hip</code>.
     */
    public String getGemGesHip() {
        return (String) get(22);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_torso</code>.
     */
    public void setGemGesTorso(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_torso</code>.
     */
    public String getGemGesTorso() {
        return (String) get(23);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_engine_heavy_mount_left</code>.
     */
    public void setGemGesEngineHeavyMountLeft(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_engine_heavy_mount_left</code>.
     */
    public String getGemGesEngineHeavyMountLeft() {
        return (String) get(24);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_engine_heavy_mount_right</code>.
     */
    public void setGemGesEngineHeavyMountRight(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_engine_heavy_mount_right</code>.
     */
    public String getGemGesEngineHeavyMountRight() {
        return (String) get(25);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_fuel_tank_storage</code>.
     */
    public void setGemGesFuelTankStorage(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_fuel_tank_storage</code>.
     */
    public String getGemGesFuelTankStorage() {
        return (String) get(26);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_left_collar_mount</code>.
     */
    public void setGemGesLeftCollarMount(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_left_collar_mount</code>.
     */
    public String getGemGesLeftCollarMount() {
        return (String) get(27);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_right_collar_mount</code>.
     */
    public void setGemGesRightCollarMount(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_right_collar_mount</code>.
     */
    public String getGemGesRightCollarMount() {
        return (String) get(28);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_leg_out_left</code>.
     */
    public void setGemGesUpperLegOutLeft(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_leg_out_left</code>.
     */
    public String getGemGesUpperLegOutLeft() {
        return (String) get(29);
    }

    /**
     * Setter for <code>tue4_gear_model.gem_ges_upper_leg_out_right</code>.
     */
    public void setGemGesUpperLegOutRight(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>tue4_gear_model.gem_ges_upper_leg_out_right</code>.
     */
    public String getGemGesUpperLegOutRight() {
        return (String) get(30);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GearModelRecord
     */
    public GearModelRecord() {
        super(Tue4GearModel.GEAR_MODEL);
    }

    /**
     * Create a detached, initialised GearModelRecord
     */
    public GearModelRecord(String id, String name, Boolean selectable, String gesEngine, String gesFuelTank, String gesPylonRight,
        String gesPylonLeft, String gesFootRight, String gesFootLeft, String gesUpperLegRight, String gesUpperLegLeft, String gesLowerLegRight,
        String gesLowerLegLeft, String gesHandRight, String gesHandLeft, String gesLowerArmRight, String gesLowerArmLeft, String gesUpperArmRight,
        String gesUpperArmLeft, String gesShoulderRight, String gesShoulderLeft, String gesHead, String gesHip, String gesTorso,
        String gesEngineHeavyMountLeft, String gesEngineHeavyMountRight, String gesFuelTankStorage, String gesLeftCollarMount,
        String gesRightCollarMount, String gesUpperLegOutLeft, String gesUpperLegOutRight) {
        super(Tue4GearModel.GEAR_MODEL);

        set(0, id);
        set(1, name);
        set(2, selectable);
        set(3, gesEngine);
        set(4, gesFuelTank);
        set(5, gesPylonRight);
        set(6, gesPylonLeft);
        set(7, gesFootRight);
        set(8, gesFootLeft);
        set(9, gesUpperLegRight);
        set(10, gesUpperLegLeft);
        set(11, gesLowerLegRight);
        set(12, gesLowerLegLeft);
        set(13, gesHandRight);
        set(14, gesHandLeft);
        set(15, gesLowerArmRight);
        set(16, gesLowerArmLeft);
        set(17, gesUpperArmRight);
        set(18, gesUpperArmLeft);
        set(19, gesShoulderRight);
        set(20, gesShoulderLeft);
        set(21, gesHead);
        set(22, gesHip);
        set(23, gesTorso);
        set(24, gesEngineHeavyMountLeft);
        set(25, gesEngineHeavyMountRight);
        set(26, gesFuelTankStorage);
        set(27, gesLeftCollarMount);
        set(28, gesRightCollarMount);
        set(29, gesUpperLegOutLeft);
        set(30, gesUpperLegOutRight);
    }
}
