/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4InventoryObject;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class InventoryObjectRecord extends UpdatableRecordImpl<InventoryObjectRecord> implements Record5<String, String, String, Long, String> {

    private static final long serialVersionUID = -141654830;

    /**
     * Setter for <code>tue4_inventory_object.ino_id</code>.
     */
    public void setInoId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_inventory_object.ino_id</code>.
     */
    @NotNull
    public String getInoId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_inventory_object.ino_name</code>.
     */
    public void setInoName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_inventory_object.ino_name</code>.
     */
    @NotNull
    public String getInoName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_inventory_object.ino_blu_master</code>.
     */
    public void setInoBluMaster(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_inventory_object.ino_blu_master</code>.
     */
    public String getInoBluMaster() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_inventory_object.ino_size</code>.
     */
    public void setInoSize(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_inventory_object.ino_size</code>.
     */
    public Long getInoSize() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>tue4_inventory_object.ino_type</code>.
     */
    public void setInoType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_inventory_object.ino_type</code>.
     */
    public String getInoType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Long, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4InventoryObject.INVENTORY_OBJECT.INO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4InventoryObject.INVENTORY_OBJECT.INO_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4InventoryObject.INVENTORY_OBJECT.INO_BLU_MASTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Tue4InventoryObject.INVENTORY_OBJECT.INO_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tue4InventoryObject.INVENTORY_OBJECT.INO_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getInoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getInoName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getInoBluMaster();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getInoSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInoType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getInoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInoName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInoBluMaster();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getInoSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInoType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord value1(String value) {
        setInoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord value2(String value) {
        setInoName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord value3(String value) {
        setInoBluMaster(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord value4(Long value) {
        setInoSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord value5(String value) {
        setInoType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryObjectRecord values(String value1, String value2, String value3, Long value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryObjectRecord
     */
    public InventoryObjectRecord() {
        super(Tue4InventoryObject.INVENTORY_OBJECT);
    }

    /**
     * Create a detached, initialised InventoryObjectRecord
     */
    public InventoryObjectRecord(String id, String name, String bluMaster, Long size, String type) {
        super(Tue4InventoryObject.INVENTORY_OBJECT);

        set(0, id);
        set(1, name);
        set(2, bluMaster);
        set(3, size);
        set(4, type);
    }
}
