/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4LoreTaxes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class LoreTaxesRecord extends UpdatableRecordImpl<LoreTaxesRecord> implements Record6<String, Integer, Integer, Double, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1159377013;

    /**
     * Setter for <code>tue4_lore_taxes.ltax_id</code>.
     */
    public void setLtaxId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.ltax_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getLtaxId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_lore_taxes.ltax_weekly</code>.
     */
    public void setLtaxWeekly(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.ltax_weekly</code>.
     */
    @NotNull
    public Integer getLtaxWeekly() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tue4_lore_taxes.ltax_annual</code>.
     */
    public void setLtaxAnnual(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.ltax_annual</code>.
     */
    @NotNull
    public Integer getLtaxAnnual() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tue4_lore_taxes.ltax_rate</code>.
     */
    public void setLtaxRate(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.ltax_rate</code>.
     */
    @NotNull
    public Double getLtaxRate() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>tue4_lore_taxes.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>tue4_lore_taxes.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_lore_taxes.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, Integer, Double, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, Integer, Double, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4LoreTaxes.LORE_TAXES.LTAX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Tue4LoreTaxes.LORE_TAXES.LTAX_WEEKLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tue4LoreTaxes.LORE_TAXES.LTAX_ANNUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Tue4LoreTaxes.LORE_TAXES.LTAX_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Tue4LoreTaxes.LORE_TAXES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Tue4LoreTaxes.LORE_TAXES.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLtaxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLtaxWeekly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getLtaxAnnual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLtaxRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLtaxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLtaxWeekly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLtaxAnnual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLtaxRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value1(String value) {
        setLtaxId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value2(Integer value) {
        setLtaxWeekly(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value3(Integer value) {
        setLtaxAnnual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value4(Double value) {
        setLtaxRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreTaxesRecord values(String value1, Integer value2, Integer value3, Double value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoreTaxesRecord
     */
    public LoreTaxesRecord() {
        super(Tue4LoreTaxes.LORE_TAXES);
    }

    /**
     * Create a detached, initialised LoreTaxesRecord
     */
    public LoreTaxesRecord(String ltaxId, Integer ltaxWeekly, Integer ltaxAnnual, Double ltaxRate, Timestamp createdAt, Timestamp updatedAt) {
        super(Tue4LoreTaxes.LORE_TAXES);

        set(0, ltaxId);
        set(1, ltaxWeekly);
        set(2, ltaxAnnual);
        set(3, ltaxRate);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
