/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4LoreCircuits;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class LoreCircuitsRecord extends UpdatableRecordImpl<LoreCircuitsRecord> implements
    Record8<String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 737952492;

    /**
     * Setter for <code>tue4_lore_circuits.lcir_id</code>.
     */
    public void setLcirId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getLcirId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_lore_circuits.lcir_lpla_id</code>.
     */
    public void setLcirLplaId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_lpla_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getLcirLplaId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_lore_circuits.lcir_hemisphere</code>.
     */
    public void setLcirHemisphere(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_hemisphere</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLcirHemisphere() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_lore_circuits.lcir_class</code>.
     */
    public void setLcirClass(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_class</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLcirClass() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_lore_circuits.lcir_league</code>.
     */
    public void setLcirLeague(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_league</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLcirLeague() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tue4_lore_circuits.lcir_name</code>.
     */
    public void setLcirName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.lcir_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLcirName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tue4_lore_circuits.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>tue4_lore_circuits.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_lore_circuits.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_LPLA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_HEMISPHERE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_LEAGUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tue4LoreCircuits.LORE_CIRCUITS.LCIR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Tue4LoreCircuits.LORE_CIRCUITS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Tue4LoreCircuits.LORE_CIRCUITS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLcirId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLcirLplaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLcirHemisphere();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLcirClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLcirLeague();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLcirName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLcirId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLcirLplaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLcirHemisphere();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLcirClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLcirLeague();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLcirName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value1(String value) {
        setLcirId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value2(String value) {
        setLcirLplaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value3(String value) {
        setLcirHemisphere(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value4(String value) {
        setLcirClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value5(String value) {
        setLcirLeague(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value6(String value) {
        setLcirName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreCircuitsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7,
        Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoreCircuitsRecord
     */
    public LoreCircuitsRecord() {
        super(Tue4LoreCircuits.LORE_CIRCUITS);
    }

    /**
     * Create a detached, initialised LoreCircuitsRecord
     */
    public LoreCircuitsRecord(String lcirId, String lcirLplaId, String lcirHemisphere, String lcirClass, String lcirLeague, String lcirName,
        Timestamp createdAt, Timestamp updatedAt) {
        super(Tue4LoreCircuits.LORE_CIRCUITS);

        set(0, lcirId);
        set(1, lcirLplaId);
        set(2, lcirHemisphere);
        set(3, lcirClass);
        set(4, lcirLeague);
        set(5, lcirName);
        set(6, createdAt);
        set(7, updatedAt);
    }
}
