/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4LoreGears;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class LoreGearsRecord extends UpdatableRecordImpl<LoreGearsRecord>
    implements
    Record19<String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1701304110;

    /**
     * Setter for <code>tue4_lore_gears.lge_id</code>.
     */
    public void setLgeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getLgeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_factions</code>.
     */
    public void setLgeFactions(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_factions</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeFactions() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_name</code>.
     */
    public void setLgeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_gem_id</code>.
     */
    public void setLgeGemId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_gem_id</code>.
     */
    @Size(max = 32)
    public String getLgeGemId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_store_order_id</code>.
     */
    public void setLgeStoreOrderId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_store_order_id</code>.
     */
    public Integer getLgeStoreOrderId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_pledge_id</code>.
     */
    public void setLgePledgeId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_pledge_id</code>.
     */
    @Size(max = 255)
    public String getLgePledgeId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_class</code>.
     */
    public void setLgeClass(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_class</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeClass() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_gear_desc</code>.
     */
    public void setLgeGearDesc(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_gear_desc</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeGearDesc() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_core</code>.
     */
    public void setLgeCore(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_core</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeCore() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_backer</code>.
     */
    public void setLgeBacker(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_backer</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeBacker() {
        return (String) get(9);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_engine_heavy_mount_left</code>.
     */
    public void setLgeEngineHeavyMountLeft(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_engine_heavy_mount_left</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeEngineHeavyMountLeft() {
        return (String) get(10);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_engine_heavy_mount_right</code>.
     */
    public void setLgeEngineHeavyMountRight(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_engine_heavy_mount_right</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeEngineHeavyMountRight() {
        return (String) get(11);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_fuel_tank_storage</code>.
     */
    public void setLgeFuelTankStorage(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_fuel_tank_storage</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeFuelTankStorage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_left_collar_mount</code>.
     */
    public void setLgeLeftCollarMount(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_left_collar_mount</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeLeftCollarMount() {
        return (String) get(13);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_right_collar_mount</code>.
     */
    public void setLgeRightCollarMount(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_right_collar_mount</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeRightCollarMount() {
        return (String) get(14);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_upper_leg_out_left</code>.
     */
    public void setLgeUpperLegOutLeft(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_upper_leg_out_left</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeUpperLegOutLeft() {
        return (String) get(15);
    }

    /**
     * Setter for <code>tue4_lore_gears.lge_upper_leg_out_right</code>.
     */
    public void setLgeUpperLegOutRight(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.lge_upper_leg_out_right</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLgeUpperLegOutRight() {
        return (String) get(16);
    }

    /**
     * Setter for <code>tue4_lore_gears.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>tue4_lore_gears.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>tue4_lore_gears.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<String, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4LoreGears.LORE_GEARS.LGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4LoreGears.LORE_GEARS.LGE_FACTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4LoreGears.LORE_GEARS.LGE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tue4LoreGears.LORE_GEARS.LGE_GEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Tue4LoreGears.LORE_GEARS.LGE_STORE_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tue4LoreGears.LORE_GEARS.LGE_PLEDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Tue4LoreGears.LORE_GEARS.LGE_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Tue4LoreGears.LORE_GEARS.LGE_GEAR_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Tue4LoreGears.LORE_GEARS.LGE_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Tue4LoreGears.LORE_GEARS.LGE_BACKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Tue4LoreGears.LORE_GEARS.LGE_ENGINE_HEAVY_MOUNT_LEFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Tue4LoreGears.LORE_GEARS.LGE_ENGINE_HEAVY_MOUNT_RIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Tue4LoreGears.LORE_GEARS.LGE_FUEL_TANK_STORAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Tue4LoreGears.LORE_GEARS.LGE_LEFT_COLLAR_MOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Tue4LoreGears.LORE_GEARS.LGE_RIGHT_COLLAR_MOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Tue4LoreGears.LORE_GEARS.LGE_UPPER_LEG_OUT_LEFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Tue4LoreGears.LORE_GEARS.LGE_UPPER_LEG_OUT_RIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Tue4LoreGears.LORE_GEARS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return Tue4LoreGears.LORE_GEARS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLgeFactions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLgeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLgeGemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLgeStoreOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLgePledgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLgeClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLgeGearDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLgeCore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLgeBacker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getLgeEngineHeavyMountLeft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getLgeEngineHeavyMountRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getLgeFuelTankStorage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getLgeLeftCollarMount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getLgeRightCollarMount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getLgeUpperLegOutLeft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getLgeUpperLegOutRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component19() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLgeFactions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLgeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLgeGemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLgeStoreOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLgePledgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLgeClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLgeGearDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLgeCore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLgeBacker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getLgeEngineHeavyMountLeft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getLgeEngineHeavyMountRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLgeFuelTankStorage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getLgeLeftCollarMount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getLgeRightCollarMount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getLgeUpperLegOutLeft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLgeUpperLegOutRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value1(String value) {
        setLgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value2(String value) {
        setLgeFactions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value3(String value) {
        setLgeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value4(String value) {
        setLgeGemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value5(Integer value) {
        setLgeStoreOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value6(String value) {
        setLgePledgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value7(String value) {
        setLgeClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value8(String value) {
        setLgeGearDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value9(String value) {
        setLgeCore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value10(String value) {
        setLgeBacker(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value11(String value) {
        setLgeEngineHeavyMountLeft(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value12(String value) {
        setLgeEngineHeavyMountRight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value13(String value) {
        setLgeFuelTankStorage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value14(String value) {
        setLgeLeftCollarMount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value15(String value) {
        setLgeRightCollarMount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value16(String value) {
        setLgeUpperLegOutLeft(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value17(String value) {
        setLgeUpperLegOutRight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value18(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord value19(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreGearsRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6, String value7,
        String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16,
        String value17, Timestamp value18, Timestamp value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoreGearsRecord
     */
    public LoreGearsRecord() {
        super(Tue4LoreGears.LORE_GEARS);
    }

    /**
     * Create a detached, initialised LoreGearsRecord
     */
    public LoreGearsRecord(String id, String factions, String name, String gemId, Integer storeOrderId, String pledgeId, String class_,
        String gearDesc, String core, String backer, String engineHeavyMountLeft, String engineHeavyMountRight, String fuelTankStorage,
        String leftCollarMount, String rightCollarMount, String upperLegOutLeft, String upperLegOutRight, Timestamp createdAt, Timestamp updatedAt) {
        super(Tue4LoreGears.LORE_GEARS);

        set(0, id);
        set(1, factions);
        set(2, name);
        set(3, gemId);
        set(4, storeOrderId);
        set(5, pledgeId);
        set(6, class_);
        set(7, gearDesc);
        set(8, core);
        set(9, backer);
        set(10, engineHeavyMountLeft);
        set(11, engineHeavyMountRight);
        set(12, fuelTankStorage);
        set(13, leftCollarMount);
        set(14, rightCollarMount);
        set(15, upperLegOutLeft);
        set(16, upperLegOutRight);
        set(17, createdAt);
        set(18, updatedAt);
    }
}
