/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4LoreStars;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class LoreStarsRecord extends UpdatableRecordImpl<LoreStarsRecord> implements
    Record7<String, String, String, String, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -891096563;

    /**
     * Setter for <code>tue4_lore_stars.lstar_id</code>.
     */
    public void setLstarId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.lstar_id</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getLstarId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_lore_stars.lstar_name</code>.
     */
    public void setLstarName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.lstar_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLstarName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_lore_stars.lstar_type</code>.
     */
    public void setLstarType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.lstar_type</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getLstarType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_lore_stars.lstar_descrip</code>.
     */
    public void setLstarDescrip(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.lstar_descrip</code>.
     */
    @NotNull
    public String getLstarDescrip() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_lore_stars.lstar_temp</code>.
     */
    public void setLstarTemp(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.lstar_temp</code>.
     */
    @NotNull
    public Long getLstarTemp() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>tue4_lore_stars.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>tue4_lore_stars.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_lore_stars.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Long, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4LoreStars.LORE_STARS.LSTAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4LoreStars.LORE_STARS.LSTAR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tue4LoreStars.LORE_STARS.LSTAR_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tue4LoreStars.LORE_STARS.LSTAR_DESCRIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Tue4LoreStars.LORE_STARS.LSTAR_TEMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Tue4LoreStars.LORE_STARS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Tue4LoreStars.LORE_STARS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLstarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLstarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLstarType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLstarDescrip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLstarTemp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLstarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLstarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLstarType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLstarDescrip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLstarTemp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value1(String value) {
        setLstarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value2(String value) {
        setLstarName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value3(String value) {
        setLstarType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value4(String value) {
        setLstarDescrip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value5(Long value) {
        setLstarTemp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoreStarsRecord values(String value1, String value2, String value3, String value4, Long value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoreStarsRecord
     */
    public LoreStarsRecord() {
        super(Tue4LoreStars.LORE_STARS);
    }

    /**
     * Create a detached, initialised LoreStarsRecord
     */
    public LoreStarsRecord(String lstarId, String lstarName, String lstarType, String lstarDescrip, Long lstarTemp, Timestamp createdAt,
        Timestamp updatedAt) {
        super(Tue4LoreStars.LORE_STARS);

        set(0, lstarId);
        set(1, lstarName);
        set(2, lstarType);
        set(3, lstarDescrip);
        set(4, lstarTemp);
        set(5, createdAt);
        set(6, updatedAt);
    }
}
