/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4Map;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class MapRecord extends UpdatableRecordImpl<MapRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1604174170;

    /**
     * Setter for <code>tue4_map.map_id</code>.
     */
    public void setMapId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_map.map_id</code>.
     */
    @NotNull
    public String getMapId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_map.map_asset_name</code>.
     */
    public void setMapAssetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_map.map_asset_name</code>.
     */
    public String getMapAssetName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4Map.MAP.MAP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4Map.MAP.MAP_ASSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMapAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMapAssetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapRecord value1(String value) {
        setMapId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapRecord value2(String value) {
        setMapAssetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapRecord
     */
    public MapRecord() {
        super(Tue4Map.MAP);
    }

    /**
     * Create a detached, initialised MapRecord
     */
    public MapRecord(String id, String assetName) {
        super(Tue4Map.MAP);

        set(0, id);
        set(1, assetName);
    }
}
