/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.util.UUID;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4MatchSessionParticipant;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class MatchSessionParticipantRecord extends UpdatableRecordImpl<MatchSessionParticipantRecord> implements
    Record4<String, UUID, Integer, Boolean> {

    private static final long serialVersionUID = 49099469;

    /**
     * Setter for <code>tue4_match_session_participant.msp_pilot_id</code>.
     */
    public void setMspPilotId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_match_session_participant.msp_pilot_id</code>.
     */
    @NotNull
    public String getMspPilotId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_match_session_participant.msp_ms_id</code>.
     */
    public void setMspMsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_match_session_participant.msp_ms_id</code>.
     */
    @NotNull
    public UUID getMspMsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>tue4_match_session_participant.msp_user_index</code>.
     */
    public void setMspUserIndex(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_match_session_participant.msp_user_index</code>.
     */
    @NotNull
    public Integer getMspUserIndex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tue4_match_session_participant.msp_active</code>.
     */
    public void setMspActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_match_session_participant.msp_active</code>.
     */
    @NotNull
    public Boolean getMspActive() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UUID, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UUID, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT.MSP_PILOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT.MSP_MS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT.MSP_USER_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT.MSP_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMspPilotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getMspMsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMspUserIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getMspActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMspPilotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getMspMsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMspUserIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getMspActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchSessionParticipantRecord value1(String value) {
        setMspPilotId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchSessionParticipantRecord value2(UUID value) {
        setMspMsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchSessionParticipantRecord value3(Integer value) {
        setMspUserIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchSessionParticipantRecord value4(Boolean value) {
        setMspActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchSessionParticipantRecord values(String value1, UUID value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchSessionParticipantRecord
     */
    public MatchSessionParticipantRecord() {
        super(Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT);
    }

    /**
     * Create a detached, initialised MatchSessionParticipantRecord
     */
    public MatchSessionParticipantRecord(String pilotId, UUID msId, Integer userIndex, Boolean active) {
        super(Tue4MatchSessionParticipant.MATCH_SESSION_PARTICIPANT);

        set(0, pilotId);
        set(1, msId);
        set(2, userIndex);
        set(3, active);
    }
}
