/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import com.tokenplay.ue4.model.db.tables.Products;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements
    Record12<Long, Long, String, BigDecimal, String, String, String, Long, OffsetDateTime, OffsetDateTime, String, BigDecimal> {

    private static final long serialVersionUID = -192440710;

    /**
     * Setter for <code>products.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>products.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>products.product_category_id</code>.
     */
    public void setProductCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>products.product_category_id</code>.
     */
    public Long getProductCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>products.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>products.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>products.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>products.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>products.thumb_image</code>.
     */
    public void setThumbImage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>products.thumb_image</code>.
     */
    public String getThumbImage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>products.main_image</code>.
     */
    public void setMainImage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>products.main_image</code>.
     */
    public String getMainImage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>products.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>products.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>products.position</code>.
     */
    public void setPosition(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>products.position</code>.
     */
    public Long getPosition() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>products.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>products.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>products.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>products.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>products.mini_description</code>.
     */
    public void setMiniDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>products.mini_description</code>.
     */
    public String getMiniDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>products.initial_tec</code>.
     */
    public void setInitialTec(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>products.initial_tec</code>.
     */
    public BigDecimal getInitialTec() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, BigDecimal, String, String, String, Long, OffsetDateTime, OffsetDateTime, String, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, BigDecimal, String, String, String, Long, OffsetDateTime, OffsetDateTime, String, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Products.PRODUCTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Products.PRODUCTS.PRODUCT_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Products.PRODUCTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Products.PRODUCTS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Products.PRODUCTS.THUMB_IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Products.PRODUCTS.MAIN_IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Products.PRODUCTS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Products.PRODUCTS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field9() {
        return Products.PRODUCTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field10() {
        return Products.PRODUCTS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Products.PRODUCTS.MINI_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return Products.PRODUCTS.INITIAL_TEC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getProductCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getThumbImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMainImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getMiniDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getInitialTec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getProductCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getThumbImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMainImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value10() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMiniDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getInitialTec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value2(Long value) {
        setProductCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value5(String value) {
        setThumbImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value6(String value) {
        setMainImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value8(Long value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value9(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value10(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value11(String value) {
        setMiniDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value12(BigDecimal value) {
        setInitialTec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord values(Long value1, Long value2, String value3, BigDecimal value4, String value5, String value6, String value7,
        Long value8, OffsetDateTime value9, OffsetDateTime value10, String value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long id, Long productCategoryId, String title, BigDecimal price, String thumbImage, String mainImage, String description,
        Long position, OffsetDateTime createdAt, OffsetDateTime updatedAt, String miniDescription, BigDecimal initialTec) {
        super(Products.PRODUCTS);

        set(0, id);
        set(1, productCategoryId);
        set(2, title);
        set(3, price);
        set(4, thumbImage);
        set(5, mainImage);
        set(6, description);
        set(7, position);
        set(8, createdAt);
        set(9, updatedAt);
        set(10, miniDescription);
        set(11, initialTec);
    }
}
