/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4Relationship;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class RelationshipRecord extends UpdatableRecordImpl<RelationshipRecord> implements Record4<String, String, OffsetDateTime, String> {

    private static final long serialVersionUID = -2071464087;

    /**
     * Setter for <code>tue4_relationship.rel_pil_id_source</code>.
     */
    public void setRelPilIdSource(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_relationship.rel_pil_id_source</code>.
     */
    @NotNull
    public String getRelPilIdSource() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_relationship.rel_pil_id_target</code>.
     */
    public void setRelPilIdTarget(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_relationship.rel_pil_id_target</code>.
     */
    @NotNull
    public String getRelPilIdTarget() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_relationship.rel_last_update</code>.
     */
    public void setRelLastUpdate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_relationship.rel_last_update</code>.
     */
    public OffsetDateTime getRelLastUpdate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>tue4_relationship.rel_status</code>.
     */
    public void setRelStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_relationship.rel_status</code>.
     */
    @NotNull
    public String getRelStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, OffsetDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, OffsetDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4Relationship.RELATIONSHIP.REL_PIL_ID_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4Relationship.RELATIONSHIP.REL_PIL_ID_TARGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return Tue4Relationship.RELATIONSHIP.REL_LAST_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tue4Relationship.RELATIONSHIP.REL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRelPilIdSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRelPilIdTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getRelLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRelStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRelPilIdSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRelPilIdTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getRelLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRelStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value1(String value) {
        setRelPilIdSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value2(String value) {
        setRelPilIdTarget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value3(OffsetDateTime value) {
        setRelLastUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value4(String value) {
        setRelStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord values(String value1, String value2, OffsetDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelationshipRecord
     */
    public RelationshipRecord() {
        super(Tue4Relationship.RELATIONSHIP);
    }

    /**
     * Create a detached, initialised RelationshipRecord
     */
    public RelationshipRecord(String pilIdSource, String pilIdTarget, OffsetDateTime lastUpdate, String status) {
        super(Tue4Relationship.RELATIONSHIP);

        set(0, pilIdSource);
        set(1, pilIdTarget);
        set(2, lastUpdate);
        set(3, status);
    }
}
