/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.tokenplay.ue4.model.db.tables.Tue4Server;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class ServerRecord extends UpdatableRecordImpl<ServerRecord> {

    private static final long serialVersionUID = 1855292326;

    /**
     * Setter for <code>tue4_server.srv_id</code>.
     */
    public void setSrvId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_server.srv_id</code>.
     */
    @NotNull
    public String getSrvId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_server.srv_name</code>.
     */
    public void setSrvName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_server.srv_name</code>.
     */
    @NotNull
    public String getSrvName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tue4_server.srv_status</code>.
     */
    public void setSrvStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tue4_server.srv_status</code>.
     */
    public String getSrvStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tue4_server.srv_ip</code>.
     */
    public void setSrvIp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tue4_server.srv_ip</code>.
     */
    @NotNull
    public String getSrvIp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tue4_server.srv_description</code>.
     */
    public void setSrvDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tue4_server.srv_description</code>.
     */
    public String getSrvDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tue4_server.srv_alias</code>.
     */
    public void setSrvAlias(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tue4_server.srv_alias</code>.
     */
    @NotNull
    public String getSrvAlias() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tue4_server.srv_last_check</code>.
     */
    public void setSrvLastCheck(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>tue4_server.srv_last_check</code>.
     */
    public OffsetDateTime getSrvLastCheck() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>tue4_server.srv_ue4_port</code>.
     */
    public void setSrvUe4Port(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tue4_server.srv_ue4_port</code>.
     */
    public String getSrvUe4Port() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tue4_server.srv_zmq_port</code>.
     */
    public void setSrvZmqPort(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tue4_server.srv_zmq_port</code>.
     */
    public String getSrvZmqPort() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tue4_server.srv_max_players</code>.
     */
    public void setSrvMaxPlayers(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>tue4_server.srv_max_players</code>.
     */
    public Long getSrvMaxPlayers() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>tue4_server.srv_running_version</code>.
     */
    public void setSrvRunningVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>tue4_server.srv_running_version</code>.
     */
    public String getSrvRunningVersion() {
        return (String) get(10);
    }

    /**
     * Setter for <code>tue4_server.srv_use_cycle</code>.
     */
    public void setSrvUseCycle(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>tue4_server.srv_use_cycle</code>.
     */
    public Boolean getSrvUseCycle() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>tue4_server.srv_sanctioned</code>.
     */
    public void setSrvSanctioned(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>tue4_server.srv_sanctioned</code>.
     */
    public Boolean getSrvSanctioned() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>tue4_server.srv_visible</code>.
     */
    public void setSrvVisible(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>tue4_server.srv_visible</code>.
     */
    public Boolean getSrvVisible() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>tue4_server.srv_pil_id</code>.
     */
    public void setSrvPilId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>tue4_server.srv_pil_id</code>.
     */
    public String getSrvPilId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>tue4_server.srv_last_use</code>.
     */
    public void setSrvLastUse(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>tue4_server.srv_last_use</code>.
     */
    public OffsetDateTime getSrvLastUse() {
        return (OffsetDateTime) get(15);
    }

    /**
     * Setter for <code>tue4_server.srv_mch_id</code>.
     */
    public void setSrvMchId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>tue4_server.srv_mch_id</code>.
     */
    public String getSrvMchId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>tue4_server.srv_development</code>.
     */
    public void setSrvDevelopment(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>tue4_server.srv_development</code>.
     */
    public Boolean getSrvDevelopment() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>tue4_server.srv_use_custom_cycle</code>.
     */
    public void setSrvUseCustomCycle(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>tue4_server.srv_use_custom_cycle</code>.
     */
    public Boolean getSrvUseCustomCycle() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>tue4_server.srv_cha_id</code>.
     */
    public void setSrvChaId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>tue4_server.srv_cha_id</code>.
     */
    public String getSrvChaId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>tue4_server.srv_max_bots</code>.
     */
    public void setSrvMaxBots(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>tue4_server.srv_max_bots</code>.
     */
    public Long getSrvMaxBots() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>tue4_server.srv_match_time</code>.
     */
    public void setSrvMatchTime(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>tue4_server.srv_match_time</code>.
     */
    public Long getSrvMatchTime() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>tue4_server.srv_map_cycle_last_index</code>.
     */
    public void setSrvMapCycleLastIndex(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>tue4_server.srv_map_cycle_last_index</code>.
     */
    public Long getSrvMapCycleLastIndex() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>tue4_server.srv_shuffle</code>.
     */
    public void setSrvShuffle(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>tue4_server.srv_shuffle</code>.
     */
    public Boolean getSrvShuffle() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>tue4_server.srv_cyclelist</code>.
     */
    public void setSrvCyclelist(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>tue4_server.srv_cyclelist</code>.
     */
    public String getSrvCyclelist() {
        return (String) get(24);
    }

    /**
     * Setter for <code>tue4_server.srv_override_map_player_count</code>.
     */
    public void setSrvOverrideMapPlayerCount(Long value) {
        set(25, value);
    }

    /**
     * Getter for <code>tue4_server.srv_override_map_player_count</code>.
     */
    public Long getSrvOverrideMapPlayerCount() {
        return (Long) get(25);
    }

    /**
     * Setter for <code>tue4_server.srv_default_map_time_limit</code>.
     */
    public void setSrvDefaultMapTimeLimit(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>tue4_server.srv_default_map_time_limit</code>.
     */
    public Long getSrvDefaultMapTimeLimit() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>tue4_server.srv_num_players</code>.
     */
    public void setSrvNumPlayers(Long value) {
        set(27, value);
    }

    /**
     * Getter for <code>tue4_server.srv_num_players</code>.
     */
    public Long getSrvNumPlayers() {
        return (Long) get(27);
    }

    /**
     * Setter for <code>tue4_server.srv_zone</code>.
     */
    public void setSrvZone(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>tue4_server.srv_zone</code>.
     */
    @Size(max = 25)
    public String getSrvZone() {
        return (String) get(28);
    }

    /**
     * Setter for <code>tue4_server.srv_password</code>.
     */
    public void setSrvPassword(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>tue4_server.srv_password</code>.
     */
    @Size(max = 75)
    public String getSrvPassword() {
        return (String) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerRecord
     */
    public ServerRecord() {
        super(Tue4Server.SERVER);
    }

    /**
     * Create a detached, initialised ServerRecord
     */
    public ServerRecord(String id, String name, String status, String ip, String description, String alias, OffsetDateTime lastCheck, String ue4Port,
        String zmqPort, Long maxPlayers, String runningVersion, Boolean useCycle, Boolean sanctioned, Boolean visible, String pilId,
        OffsetDateTime lastUse, String mchId, Boolean development, Boolean useCustomCycle, String chaId, Long maxBots, Long matchTime,
        Long mapCycleLastIndex, Boolean shuffle, String cyclelist, Long overrideMapPlayerCount, Long defaultMapTimeLimit, Long numPlayers,
        String zone, String password) {
        super(Tue4Server.SERVER);

        set(0, id);
        set(1, name);
        set(2, status);
        set(3, ip);
        set(4, description);
        set(5, alias);
        set(6, lastCheck);
        set(7, ue4Port);
        set(8, zmqPort);
        set(9, maxPlayers);
        set(10, runningVersion);
        set(11, useCycle);
        set(12, sanctioned);
        set(13, visible);
        set(14, pilId);
        set(15, lastUse);
        set(16, mchId);
        set(17, development);
        set(18, useCustomCycle);
        set(19, chaId);
        set(20, maxBots);
        set(21, matchTime);
        set(22, mapCycleLastIndex);
        set(23, shuffle);
        set(24, cyclelist);
        set(25, overrideMapPlayerCount);
        set(26, defaultMapTimeLimit);
        set(27, numPlayers);
        set(28, zone);
        set(29, password);
    }
}
