/*
 * This file is generated by jOOQ.
 */
package com.tokenplay.ue4.model.db.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import com.tokenplay.ue4.model.db.tables.Tue4Stable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
    "http://www.jooq.org", "jOOQ version:3.10.6"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({
    "all", "unchecked", "rawtypes"})
public class StableRecord extends UpdatableRecordImpl<StableRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1599838109;

    /**
     * Setter for <code>tue4_stable.sta_id</code>.
     */
    public void setStaId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tue4_stable.sta_id</code>.
     */
    @NotNull
    public String getStaId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tue4_stable.sta_name</code>.
     */
    public void setStaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tue4_stable.sta_name</code>.
     */
    @NotNull
    public String getStaName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tue4Stable.STABLE.STA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tue4Stable.STABLE.STA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getStaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StableRecord value1(String value) {
        setStaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StableRecord value2(String value) {
        setStaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StableRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StableRecord
     */
    public StableRecord() {
        super(Tue4Stable.STABLE);
    }

    /**
     * Create a detached, initialised StableRecord
     */
    public StableRecord(String id, String name) {
        super(Tue4Stable.STABLE);

        set(0, id);
        set(1, name);
    }
}
